      REAL FUNCTION NAT2INT
*********************************************************
*                                                       *
* This file was generated by HUWFUN.                    *
*                                                       *
*********************************************************
*
*     Ntuple Id:      10   
*     Ntuple Title:   CERN Population
*     Creation:       15/03/96 09.53.34
*
*********************************************************
*
      LOGICAL         CHAIN
      CHARACTER*128   CFILE
      INTEGER         IDNEVT,NCHEVT,ICHEVT
      REAL            OBS(13)
*
      COMMON /PAWIDN/ IDNEVT,OBS
      COMMON /PAWCHN/ CHAIN, NCHEVT, ICHEVT
      COMMON /PAWCHC/ CFILE
*
*--   Ntuple Variable Declarations
*
      INTEGER CATEGORY,FLAG,AGE,SERVICE,CHILDREN,GRADE,STEP,HRWEEK,COST
      CHARACTER*32 DIVISION,NATION
*
      COMMON /PAWCR4/ CATEGORY,FLAG,AGE,SERVICE,CHILDREN,GRADE,STEP
     + ,HRWEEK,COST
      COMMON /PAWC32/ DIVISION,NATION
*
      CHARACTER*4 NAT(15)
      DATA NAT /'DE','CH','FR','IT','NL','GB','AT','BE','NO','ES'
     +,         'DK','SE','GR','ZZ','PT'/

*
*--   Enter user code here
*
      DO I=1,15
         IF(NAT(I).EQ.NATION)THEN
           NAT2INT = FLOAT(I)
           GOTO 99
         ENDIF
      ENDDO
      NAT2INT = 0.
*
  99  END
