*
* $Id$
*
* $Log$
* Revision 1.1  1995/10/24 10:22:19  cernlib
* Initial revision
*
*
*   (BOOT WORK)
*
* bootwk.inc
*
      COMMON/BOOTWK/JBOOT,EINCID
C----------------------------------------------------------------------
C     BOOTSTRAP COMMON : JBOOT  = BOOTSTRAP BANK ADRESS
C                        EINCID = TOTAL ENERGY OF PRIMARY  PARTICLE
C----------------------------------------------------------------------
