*
* $Id$
*
* $Log$
* Revision 1.1  1996/03/06 10:47:02  mclareni
* Initial revision
*
*
*   DIVISION PARAMETERS  + explanation
*
* divparq.inc
*

      PARAMETER ( JDVBFQ = 1 )
      PARAMETER ( NDVBFQ = 1 )
      PARAMETER ( IDVFWQ = 0 )
      PARAMETER ( IDVBWQ = 1 )
      PARAMETER ( IDVUSQ =  1 )
      PARAMETER ( IDVLGQ =  2 )
      PARAMETER ( IDVPAQ =  3 )
      PARAMETER ( IDVSYQ =  4 )
      PARAMETER ( JDVIDQ =  1 )
      PARAMETER ( NDVIDQ = 20 )
      PARAMETER ( JDVUSQ = 21 )
      PARAMETER ( JDVLGQ = 22 )
      PARAMETER ( JDVPAQ = 23 )
      PARAMETER ( JDVSYQ = 24 )

      PARAMETER ( MDVLWQ =  1 )
      PARAMETER ( MDVHGQ =  2 )

