*
* $Id$
*
* $Log$
* Revision 1.1  1996/01/16 17:07:50  mclareni
* Initial revision
*
*
#ifndef CERNLIB_HBOOK_HCFIT2_INC
#define CERNLIB_HBOOK_HCFIT2_INC
*
*
* hcfit2.inc
*
*CMZ :  4.19/00 13/04/93  16.36.40  by  Rene Brun
*-- Author :
      COMMON/HCFIT2/ENDFLG,NA,INDFLG(5),IFLFUN,NAMFUN,IDIMPN,XFUMIL(10),
     +        NUMEP ,XMIN  ,EPSW  ,ALLCHA,BINWID,WGTMAX,YMIN,BINWIY,
     +       NCHANX,LINEAR,IFLSF ,IFLBUF,IDER,IWEIGH,ITFUM,ISUPIM
*

#endif
