*
* $Id$
*
* $Log$
* Revision 1.1  1996/01/16 17:07:50  mclareni
* Initial revision
*
*
#ifndef CERNLIB_HBOOK_HCFLAG_INC
#define CERNLIB_HBOOK_HCFLAG_INC
*
*
* hcflag.inc
*
*CMZ :  4.19/00 13/04/93  16.36.40  by  Rene Brun
*-- Author :
      INTEGER       ID    ,IDBADD,LID   ,IDLAST,IDHOLD,NBIT  ,NBITCH,
     +       NCHAR ,NRHIST,IERR  ,NV
      COMMON/HCFLAG/ID    ,IDBADD,LID   ,IDLAST,IDHOLD,NBIT  ,NBITCH,
     +       NCHAR ,NRHIST,IERR  ,NV
*

#endif
