*
* $Id$
*
* $Log$
* Revision 1.1  1996/05/21 08:39:53  cernlib
* Initial revision
*
* Revision 1.1  1994/10/07  23:57:37  zfiles
* New include files for QQ.
*
*
*CMZ :  1.02/61 03/10/94  17.34.58  by  Paul Avery
*CMZ :          08/10/93  11.29.57  by  Paul Avery
*>> Author :
*
*  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
*                         QQIPCD.INC
*
*         Points from full track list to CD track.
*  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
*
*  IPCDQQ(IT)          CD track number (0 if none)

      INTEGER IPCDQQ
      COMMON/QQIPC1/
     *   IPCDQQ(MCTRK)
