*
* $Id$
*
* $Log$
* Revision 1.1  1996/05/21 08:39:53  cernlib
* Initial revision
*
* Revision 1.1.1.1  1994/10/08  02:21:33  zfiles
* first version of qqlib in CVS
*
*
*CMZ :  1.04/00 15/10/93  09.31.21  by  Paul Avery
*-- Author :
*
*  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
*                         QQMXCP.INC
*
*   Contains info on mixing and CP violation within an event
*  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
*
*  ILDECA(*)      Decay channel of particle from mixing/CP
*  CTTAU(*)       Generated C*T in center of mass using mixing/CP info

      INTEGER ILDECA
      REAL CTTAU
      COMMON /QQMXC1/
     *  ILDECA(250), CTTAU(250)
