*
* $Id$
*
* $Log$
* Revision 1.1  1996/05/21 08:39:53  cernlib
* Initial revision
*
* Revision 1.1.1.1  1994/10/08  02:21:33  zfiles
* first version of qqlib in CVS
*
*
*CMZ :  1.04/00 21/09/94  22.55.57  by  Paul Avery
*-- Author :    Lynn Garren   06/12/93
*
*  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
*                      QQWJET.INC
*
*       LOCAL VARIABLES THAT ARE USED IN  SUBROUTINE  WJET
*  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
*
      REAL BQMAS
      COMMON /WWJET/BQMAS(7)

C---------------------------------------------------------------------
