*
* $Id$
*
* $Log$
* Revision 1.1  1996/03/04 16:12:57  mclareni
* Initial revision
*
*
#ifndef CERNLIB_DZDOC_BKNUPARQ_INC
#define CERNLIB_DZDOC_BKNUPARQ_INC
*
*   Description of the number special identifiers
*
* bknuparq.inc
*
 
C--               Indefinite (* given in number field)
      PARAMETER ( INUINQ = -1)
C--               Tag (non-numeric description given in number field)
      PARAMETER ( INUTGQ = -2)
 

#endif
