*
* $Id$
*
* $Log$
* Revision 1.1  1996/03/04 16:12:57  mclareni
* Initial revision
*
*
#ifndef CERNLIB_DZDOC_DZDOCC_INC
#define CERNLIB_DZDOC_DZDOCC_INC
*
*
* dzdocc.inc
*
      INTEGER        LDQBKD,LBQBKD,LDOC,LLTOP,LQBKD,LQBKD1,
     &               LUP,LORIG,LSAME,LNEW,LT,LD1,LD2,
     &               LUPD,LTD,LDD1,LDUMMY
 
      COMMON /DZDOCC/LDQBKD,LBQBKD,LDOC,LLTOP,LQBKD,LQBKD1,
     &               LUP,LORIG,LSAME,LNEW,LT,LD1,LD2,
     &               LUPD,LTD,LDD1,LDUMMY

#endif
