*
* $Id$
*
* $Log$
* Revision 1.1  1996/03/07 15:17:57  mclareni
* Initial revision
*
*
#ifndef CERNLIB_FATMEN_FTTBUG_INC
#define CERNLIB_FATMEN_FTTBUG_INC
*
*
* fttbug.inc
*
      INTEGER         IDEBFA, IDIVFA, IKDRFA, KOFSFA, KOFUFA, LBFXFA
     +              , LSAVFA, LTOPFA, LBBKFA, LBGNFA, LTDSFA, LBDSFA
     +              , LPRTFA, NTOPFA, LUFZFA, IOUPFA, IOBKFA, IODSFA
     +              , LLNLFA, LLNHFA

#endif
