CDECK  ID>, DPEXGO.
      SUBROUTINE DPEXGO

C-    DPEXE/DPMIX  READY TO WRITE FIRST CARD OF NEW ROUTINE

      COMMON /QBCD/  IQNUM2(11),IQLETT(26),IQNUM(10),IQPLUS
     +,              IQMINS,IQSTAR,IQSLAS,IQOPEN,IQCLOS,IQDOLL,IQEQU
     +,              IQBLAN,IQCOMA,IQDOT,IQAPO,  IQCROS
      PARAMETER      (IQBITW=32, IQBITC=8, IQCHAW=4)
      COMMON /QMACH/ NQBITW,NQCHAW,NQLNOR,NQLMAX,NQLPTH,NQRMAX,QLPCT
     +,              NQOCT(3),NQHEX(3),NQOCTD(3)
      COMMON /DPLINE/LTK,NWTK, KIMAPR(3), KIMA(20), KIMAPS(9)
      COMMON /IOFCOM/IOTALL,IOTOFF,IOTON,IOSPEC,IOPARF(5),IOMODE(12)
      PARAMETER      (KDNWT=20, KDNWT1=19,KDNCHW=4, KDBITS=8)
      PARAMETER      (KDPOST=25,KDBLIN=32,KDMARK=0, KDSUB=63,JPOSIG=1)
      COMMON /KDPKCM/KDBLAN,KDEOD(2)
      PARAMETER      (IQBDRO=25, IQBMAR=26, IQBCRI=27, IQBSYS=31)
      COMMON /QBITS/ IQDROP,IQMARK,IQCRIT,IQZIM,IQZIP,IQSYS
                         DIMENSION    IQUEST(30)
                         DIMENSION                 LQ(99), IQ(99), Q(99)
                         EQUIVALENCE (QUEST,IQUEST),    (LQUSER,LQ,IQ,Q)
      COMMON //      QUEST(30),LQUSER(7),LQMAIN,LQSYS(24),LQPRIV(7)
     +,              LQ1,LQ2,LQ3,LQ4,LQ5,LQ6,LQ7,LQSV,LQAN,LQDW,LQUP
     +, KADRV(9), LEXD,LEXH,LEXP,LPAM,LDECO, LADRV(14)
     +, NVOPER(6),MOPTIO(31),JANSW,JCARD,NDECKR,NVUSEB(14),MEXDEC(6)
     +, NVINC(6),NVUTY(16),NVIMAT(6),NVACT(6),NVGARB(6),NVWARN(6)
     +, NVARRQ(6),NVARR(10),IDARRV(10),NVARRI(12),NVCCP(10)
     +, NVDEP(14),LDPMAT,JDPMAT,LDPACT,JDPACT,NDPLEV,MDEPAR, NVDEPL(6)
     +, MWK(80),MWKX(80)
      EQUIVALENCE(LSASM,LADRV(8)),  (LRBIG,LADRV(13)), (LRPAM,LADRV(14))
C--------------    END CDE                             -----------------  ------
      EQUIVALENCE (LASM,NVDEP(2)), (LUNASM,NVDEP(3))


C--                ACTION  IF FIRST DECK ON THIS STREAM

      IF (IQ(LASM+2).GE.0)   GO TO 31
      J = IQ(LASM+1)
      L = IQ(LSASM-J)
      IF (IQ(L+2).GE.0)      GO TO 24
      CALL IOFILE (324,IQ(L+5))
C-                 324 = 4 CARDS, 64 OUTPUT, 256 INITIAL
      IQ(L+2)    = 0
   24 IQ(LASM+2) = 0
      IQ(LASM+5) = IQ(L+5)

   31 LUNASM = IQ(LASM+5)
      IQ(LASM+3)= IQ(LASM+3) + 1
C     IQ(LEXP+1)= IQ(LEXP+1) .OR. 4                                      MSKC
      CALL SBIT1 (IQ(LEXP+1),3)                                         -MSK
      L = IQ(LASM-1)
      IF (L.EQ.0)            RETURN
      IF (NVOPER(3).NE.0)    RETURN


C--                WRITE ROUTINE HEADER CARD IF NEEDED

      NCH  = IQ(L+1)
      NCH2 = IQ(L+2)
      IF (NCH.NE.0)  CALL UBLOW (IQ(L+4),MWKX(1),NCH)
      IF (NCH2.LT.0)         GO TO 41
      CALL UBLOW (NVDEP(7),MWKX(NCH+1),8)
      NCH = NCH + 9
   36 NCH = NCH - 1
      IF (MWKX(NCH).EQ.IQBLAN)  GO TO 36
      IF (NCH2.EQ.0)         GO TO 41
      J = L + IQ(L+3)
      CALL UBLOW (IQ(J),MWKX(NCH+1),NCH2)
      NCH = NCH + NCH2

   41 CALL UBUNCH (MWKX(1),KIMA(1),NCH)
      N = (NCH-1)/IQCHAW + 1
      CALL XOUTCF (LUNASM,KIMA(1),N)
      NVDEP(1) = 1
      RETURN

      END
