CDECK  ID>, DPEXE.
      SUBROUTINE DPEXE

C-    +EXE  OUTPUT FOR A BUNCH OF CARDS, CALLED FROM DEPART
C-                 NEEDS LDPMAT, NVDEP(12)

      PARAMETER      (IQBITW=32, IQBITC=8, IQCHAW=4)
      COMMON /QMACH/ NQBITW,NQCHAW,NQLNOR,NQLMAX,NQLPTH,NQRMAX,QLPCT
     +,              NQOCT(3),NQHEX(3),NQOCTD(3)
      COMMON /DPLINE/LTK,NWTK, KIMAPR(3), KIMA(20), KIMAPS(9)
      PARAMETER      (IQBDRO=25, IQBMAR=26, IQBCRI=27, IQBSYS=31)
      COMMON /QBITS/ IQDROP,IQMARK,IQCRIT,IQZIM,IQZIP,IQSYS
                         DIMENSION    IQUEST(30)
                         DIMENSION                 LQ(99), IQ(99), Q(99)
                         EQUIVALENCE (QUEST,IQUEST),    (LQUSER,LQ,IQ,Q)
      COMMON //      QUEST(30),LQUSER(7),LQMAIN,LQSYS(24),LQPRIV(7)
     +,              LQ1,LQ2,LQ3,LQ4,LQ5,LQ6,LQ7,LQSV,LQAN,LQDW,LQUP
     +, KADRV(9), LEXD,LEXH,LEXP,LPAM,LDECO, LADRV(14)
     +, NVOPER(6),MOPTIO(31),JANSW,JCARD,NDECKR,NVUSEB(14),MEXDEC(6)
     +, NVINC(6),NVUTY(16),NVIMAT(6),NVACT(6),NVGARB(6),NVWARN(6)
     +, NVARRQ(6),NVARR(10),IDARRV(10),NVARRI(12),NVCCP(10)
     +, NVDEP(14),LDPMAT,JDPMAT,LDPACT,JDPACT,NDPLEV,MDEPAR, NVDEPL(6)
     +, MWK(80),MWKX(80)
C--------------    END CDE                             -----------------  ------
      EQUIVALENCE (LASM,NVDEP(2)), (LUNASM,NVDEP(3))
      CHARACTER    CHIMA*80
      EQUIVALENCE (CHIMA,KIMA)

      IF (NVDEP(1).EQ.0)     GO TO 71
   11 LTK   = LDPMAT
      NCD   = NVDEP(12)
      NVDEP(1)= NVDEP(1) + NCD

      DO 24  JJ=1,NCD
      CALL KDCOPY (IQ(LTK))
      N  = LNBLNK (CHIMA(1:IQCHAW*NWTK))
      IF (N.NE.0)  THEN
          WRITE (LUNASM, 9024) CHIMA(1:N)
        ELSE
          WRITE (LUNASM, 9024)
        ENDIF
 9024 FORMAT (A)
   24 CONTINUE
      RETURN

C----              NEW DECK, START ASM IF VERY FIRST

   71 CALL DPEXGO
      GO TO 11

      END
