CDECK  ID>, FRSETU.
      SUBROUTINE FRSETU

C-    DECIDE CETA FORMAT, READY CONVERSION TABLES FOR YFRCETA

      COMMON /QBCD/  IQNUM2(11),IQLETT(26),IQNUM(10),IQPLUS
     +,              IQMINS,IQSTAR,IQSLAS,IQOPEN,IQCLOS,IQDOLL,IQEQU
     +,              IQBLAN,IQCOMA,IQDOT,IQAPO,  IQCROS
      COMMON /QUNIT/ IQREAD,IQPRNT,IQPR2,IQLOG,IQPNCH,IQTTIN,IQTYPE
     +,              IQDLUN,IQFLUN,IQHLUN,IQCLUN,  NQUSED
      COMMON /ARRCOM/LUNPAM,NCHKD,NWKD,NCARDP,NAREOF,NSKIPR,KDHOLD(20)
     +,              NTRUNC,IPROMU,IPROMI
      COMMON /CCPARA/NCHCCD,NCHCCT,KARDCC(84),   JCCTYP,JCCPRE,JCCEND
     +,              MCCPAR(120),NCCPAR,MXCCIF,JCCIFV,JCCBAD,JCCWK(4)
     +,              JCCPP,JCCPD,JCCPZ,JCCPT,JCCPIF,JCCPC,JCCPN
     +,              NCCPP,NCCPD,NCCPZ,NCCPT,NCCPIF,NCCPC,NCCPN
      COMMON /CCTYPE/MCCQUI,MCCPAM,MCCTIT,MCCPAT,MCCDEC,MCCDEF,MCCEOD
     +,              MCCASM,MCCOPT,MCCUSE
      COMMON /COMCET/INILEV,NWCEIN,NCHCEU,NWCEU
     +,              NWCEBA,IPAKCE(5),IPAKKD(5),JPOSA1,MXINHO
     +,              LCESAV(4)
      COMMON /IOFCOM/IOTALL,IOTOFF,IOTON,IOSPEC,IOPARF(5),IOMODE(12)
      PARAMETER      (KDNWT=20, KDNWT1=19,KDNCHW=4, KDBITS=8)
      PARAMETER      (KDPOST=25,KDBLIN=32,KDMARK=0, KDSUB=63,JPOSIG=1)
      COMMON /KDPKCM/KDBLAN,KDEOD(2)
      PARAMETER      (IQBDRO=25, IQBMAR=26, IQBCRI=27, IQBSYS=31)
      COMMON /QBITS/ IQDROP,IQMARK,IQCRIT,IQZIM,IQZIP,IQSYS
                         DIMENSION    IQUEST(30)
                         DIMENSION                 LQ(99), IQ(99), Q(99)
                         EQUIVALENCE (QUEST,IQUEST),    (LQUSER,LQ,IQ,Q)
      COMMON //      QUEST(30),LQUSER(7),LQMAIN,LQSYS(24),LQPRIV(7)
     +,              LQ1,LQ2,LQ3,LQ4,LQ5,LQ6,LQ7,LQSV,LQAN,LQDW,LQUP
     +, KADRV(14),LADRV(11),LCCIX,LBUF,LLAST
     +, NVOPER(6),MOPTIO(31),JANSW,JCARD,NDECKR,NVUSEX(20)
     +, NVINC(6),NVUTY(17),IDEOF(9),NVPROX(6),LOGLVG,LOGLEV,NVWARX(6)
     +, NVOLDQ(6), NVOLD(10), IDOLDV(10), NVARRI(12), NVCCP(10)
     +, NVNEW(10), IDNEWV(10), NVNEWL(6),  MWK(80),MWKX(80)
      EQUIVALENCE (LORGH,LQPRIV(1)), (LORGI,LQPRIV(2))
     +,           (LXREF,LQPRIV(3)), (LTOCE,LQPRIV(4))
     +,           (LCETA,LQPRIV(7))
C--------------    END CDE                             --------------


      IF (INILEV-2)          10,31,89
   10 INILEV = 2

      IOSPEC = MOPTIO(1)
      CALL AUXFIL (128,NVOLD(1),4HCETA)

C--------          CHOOSE CETA FORMAT

      WRITE (IQPRNT,9010)
 9010 FORMAT (1X/20X,'Ready CETA conversion, set Init-level to 2')

      NCHCEU = 3600
      NWCEU  = 5*NWCEBA
      IF (MOPTIO(21).NE.0)  WRITE (IQPRNT,9013)
 9013 FORMAT (20X,'OPTION U - NOT POSSIBLE.')

C--                HANDLE OPTIONS  BACK, XTEND, SIX

      IF (MOPTIO(2)+MOPTIO(25).NE.0)  WRITE (IQPRNT,9014)
 9014 FORMAT (20X,'!!!  Obsolete options BACK / Y ignored  !!!!')
      IF (MOPTIO(20).NE.0)  WRITE (IQPRNT,9017)
 9017 FORMAT (20X,'Option T - True control-codes go to PAM file.')

C--                INIT OF FRCETA

      NCHKD = -5
      CALL FRCETA (IQUEST)

C----------------  COMPLETE SETUP OF CONVERSION TABLES

C--                CONVERT TO UPPER CASE IF OPTION 1

      IF (MOPTIO(28).EQ.0)          GO TO 24
      DO 22  JJ=65,90
   22 IQ(LXREF+JJ) = JJ - 64
      WRITE (IQPRNT,9022)
 9022 FORMAT (1X/20X,'CONVERT LOWER CASE LETTERS TO UPPER.')

C--                CONVERT TO LOWER CASE IF OPTION 2

   24 IF (MOPTIO(29).EQ.0)          GO TO 26
      DO 25  JJ=1,26
   25 IQ(LXREF+JJ) = JJ + 64
      WRITE (IQPRNT,9025)
 9025 FORMAT (1X/20X,'CONVERT UPPER CASE LETTERS TO LOWER.')
   26 CONTINUE
      JSUB = 193
      IF (MOPTIO(20).NE.0)  JSUB=512
C--                SELECT ESCAPE REPRES. IF 6-BIT OR IF NOT OPTION TRUE

      DO 28  JJ=64,255
      J = IQ(LXREF+JJ+256)
      IF (J.EQ.0)              GO TO 28
      IF (IQ(LORGI+JJ).EQ.-1)  GO TO 27
      IF   (JJ.GE.JSUB)        GO TO 27
      IQ(LXREF+JJ) = JJ
      GO TO 28

   27 IQ(LXREF+JJ) = J + 1000
   28 CONTINUE

      IQ(LORGH) = IQ(LORGH+57)


C------------  HANDLE  +OPTION, CONVERT  /,N=C1-I1,... /OR/ .C1I1...

   31 IF (NCCPN.LT.0)        GO TO 81
      IF (JCCTYP.NE.MCCOPT)  GO TO 81
      NG = 0
      IF (NCCPN.EQ.0)        GO TO 34
      JT = JCCPN

      DO 33  J=1,NCCPN
      MWK(NG+1) = MCCPAR(JT+1)
      MWK(NG+2) = MCCPAR(JT+2)
      JT = JT + 3
   33 NG = NG + 2
      GO TO 40

   34 N = NCHCCT+1 - NCHCCD
      IF (N.LT.3)            GO TO 81
      CALL UCOPY  (KARDCC(NCHCCD+1),MWKX(1),N)
      MWKX(N) = IQBLAN
      CALL ULEFT  (MWKX,1,N)
      CALL HOLLCV (MWKX(1),MWK(1),N,1)
      N = N - 1

      DO 35  J=1,N,2
      JJ = MWK(J)
      MWK(J) = IQ(LTOCE+JJ)
      IF (MWK(J).EQ.45)      GO TO 39
      JJ = MWK(J+1)
      JJ = IQ(LTOCE+JJ)
      IF (JJ.EQ.45)          GO TO 39
   35 NG = NG + 2
   39 IF (NG.EQ.0)           GO TO 81

C----              UP-DATE  XREF  TABLE

   40 DO 49  J=1,NG,2
      NADDH = 0
      JINHO = MWK(J+1)
      JCETA = MWK(J)

      IF (JCETA.LE.0)        GO TO 48
      IF (JCETA.GE.256)      GO TO 48

      IF (JINHO.LT.1000)     GO TO 44
      NADDH = 1000
      JINHO = JINHO - 1000

   44 IF (JINHO.LT.0)        GO TO 48
      IF (JINHO.GT.MXINHO)   GO TO 48
      IF (JINHO.EQ.KDMARK)   GO TO 48
      JCETU = IQ(LTOCE+JINHO)
      IF (JCETU.NE.0)        GO TO 46

C--                CREATE NEW CHARACTER

      IF (NADDH.NE.0)        GO TO 48
      JCETU = JCETA
      IF (IQ(LORGI+JCETU).EQ.-1)  GO TO 45
      JCETU = IUCOMP (-1,IQ(LORGI+96),100)
      IF (JCETU.EQ.0)        GO TO 48
      JCETU = JCETU + 95

   45 IQ(LORGI+JCETU) = JINHO
      IQ(LTOCE+JINHO) = JCETU

C--                SET  XREF  ENTRY

   46 IQ(LXREF+JCETA) = JCETU + NADDH

      JINHO = JINHO + NADDH
      WRITE (IQPRNT,9046)  JCETA,JINHO
      GO TO 49

   48 JINHO = JINHO + NADDH
      WRITE (IQPRNT,9048)  JCETA,JINHO
   49 CONTINUE
      WRITE (IQPRNT,9049)

C----              COMPLETE HOLLERITH REPRESENTATION

   81 J = IUCOMP (KDMARK,IQ(LORGI+1),255)
      IF (J.EQ.0)            GO TO 83
      IQ(LORGI+J) = KDSUB
      GO TO 81

   83 CALL HOLLCV (IQ(LORGI+1),IQ(LORGH+1),255,0)
   89 CALL LOGLV  (MOPTIO(31),0,0)
      RETURN

 9046 FORMAT (24X,4HCETA,I5,'  GIVES INTERNAL',I5)
 9048 FORMAT (4H ***/4H ***,20X,4HCETA,I5,'     TO INTERNAL',I5,
     F'  IS IMPOSSIBLE.',24X,'*******')
 9049 FORMAT (1X)
      END
