CDECK  ID>, KDNGO.
      SUBROUTINE KDNGO

C-    INITIATE  KDNEXT-FILE

      COMMON /QUNIT/ IQREAD,IQPRNT,IQPR2,IQLOG,IQPNCH,IQTTIN,IQTYPE
     +,              IQDLUN,IQFLUN,IQHLUN,IQCLUN,  NQUSED
      COMMON /ARRCOM/LUNPAM,NCHKD,NWKD,NCARDP,NAREOF,NSKIPR,KDHOLD(20)
     +,              NTRUNC,IPROMU,IPROMI

      IPROMU = 0
      IF (LUNPAM.EQ.IQTTIN) IPROMU=IPROMI
      RETURN
      END
