CDECK  ID>, KDNREW.
      SUBROUTINE KDNREW

C-    REWIND  KDNEXT-FILE

      COMMON /ARRCOM/LUNPAM,NCHKD,NWKD,NCARDP,NAREOF,NSKIPR,KDHOLD(20)
     +,              NTRUNC,IPROMU,IPROMI

      REWIND LUNPAM
      RETURN
      END
