CDECK  ID>, MQINIT.
      SUBROUTINE MQINIT (LAST)

C-    INITIALISE MEMORY MANAGER,  USER CALLED

      PARAMETER      (NQFNAE=2, NQFNAD=1, NQFNAU=3)
      PARAMETER      (IQFSTR=19, NQFSTR=6,  IQFSYS=25, NQFSYS=8)
      COMMON /MQCF/  NQNAME,NQNAMD,NQNAMU, IQSTRU,NQSTRU, IQSYSB,NQSYSB
      COMMON /MQCMOV/NQSYSS
      COMMON /MQCM/         NQSYSR,NQSYSL,NQLINK,LQWORG,LQWORK,LQTOL
     +,              LQSTA,LQEND,LQFIX,NQMAX, NQRESV,NQMEM,LQADR,LQADR2
      COMMON /MQCT/  IQTBIT,IQTVAL,LQTA,LQTB,LQTE,LQMTB,LQMTE,LQMTH
     +,              IQPART,NQFREE
      COMMON /QBCD/  IQNUM2(11),IQLETT(26),IQNUM(10),IQPLUS
     +,              IQMINS,IQSTAR,IQSLAS,IQOPEN,IQCLOS,IQDOLL,IQEQU
     +,              IQBLAN,IQCOMA,IQDOT,IQAPO,  IQCROS
      COMMON /QCN/   IQLS,IQID,IQNL,IQNS,IQND,IQFOUL
      PARAMETER      (IQBITW=32, IQBITC=8, IQCHAW=4)
      COMMON /QMACH/ NQBITW,NQCHAW,NQLNOR,NQLMAX,NQLPTH,NQRMAX,QLPCT
     +,              NQOCT(3),NQHEX(3),NQOCTD(3)
      COMMON /QSTATE/QVERSN,NQINIT,NQSTAG(2),NQPHAS,NQERR,QDEBUG,NQDCUT
     +,              NQNEWB,NQAFTB,NQM99,NQLOWB,NQWCUT,NQLOCK,QSTDUM
     +,              NQAUGM(2),NQZIP(8),AQMEM(12)
                         INTEGER QDEBUG
      COMMON /QUNIT/ IQREAD,IQPRNT,IQPR2,IQLOG,IQPNCH,IQTTIN,IQTYPE
     +,              IQDLUN,IQFLUN,IQHLUN,IQCLUN,  NQUSED
      COMMON /QHEADP/IQHEAD(20),IQDATE,IQTIME,IQPAGE,NQPAGE(4)
      PARAMETER      (IQBDRO=25, IQBMAR=26, IQBCRI=27, IQBSYS=31)
      COMMON /QBITS/ IQDROP,IQMARK,IQCRIT,IQZIM,IQZIP,IQSYS
                         DIMENSION    IQUEST(30)
                         DIMENSION                 LQ(99), IQ(99), Q(99)
                         EQUIVALENCE (QUEST,IQUEST),    (LQUSER,LQ,IQ,Q)
      COMMON /SQK/   KQMAIN,KQT,KQR,KQJ,KQF,KQZ,KQH(4),KQS(8)
      COMMON //      QUEST(30),LQUSER(7),LQMAIN,LQT,LQR,LQJ,LQF,LQZ
     +,              LQH(4),LQS(6),   LQWM,LQWF,LQWZ,LQWSYS(6),LQPRIV(7)
     +,              LQ1,LQ2,LQ3,LQ4,LQ5,LQ6,LQ7,LQSV,LQAN,LQDW,LQUP
     +,              USER(9)
C--------------    END CDE                             -----------------  ------
      DIMENSION    KVECT(9), LAST(9)
      EQUIVALENCE (KVECT(1),KQMAIN)
      DIMENSION    LETSET(3)


      DIMENSION    MCF(7), IMACH(16), IUNIT(5), ISTATB(6)
      DATA  MCF    /2,1,3,19,6,25,8/
      DATA  ISTATB /25,26,27,28,29,31/
      DATA  IMACH  /32,4,108,110,0,132,1H ,3,10,7,4,8,15,6,5,63/
      DATA  IUNIT  /2,3,4,5,6/
C
C     NQLNOR = 108 normal number of lines per page
C     NQLMAX = 110 maximum number of lines per page
C     NQLPTH = 0   number of lines taken by the page-throw
C
C     IQREAD = 2   LUN for 'CARD READER'
C     IQPRNT = 3   LUN for 'LINE PRINTER'
C     IQTTIN = 5   LUN for TERMINAL INPUT
C     IQTYPE = 6   LUN for TERMINAL OUTPUT

      DATA  LETSET /4HXPRN, 4HXSET, 4HSET /
      DATA  INIT   /4HINIT /



      CALL UCTOH1
     + (' 1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+-*/()$= ,.'
     +,            IQNUM2(1),58)
      CALL UBLOW (4H'+  , IQAPO, 2)

      CALL UCOPY (MCF,   NQNAME,7)
      CALL UCOPY (IMACH, NQBITW,16)
      CALL UCOPY (ISTATB,IQDROP,6)
      CALL VZERO (NQINIT,36)

      NQMEM = 100
      NQINIT= 1
      NQRESV= 0
      NQDCUT= 201
      NQWCUT= 500
      NQAFTB= 7
      NQNEWB= 7

C--                READY /QNATUR/


C--                READY COMMONS /QUNIT/ + /QHEADP/

      IQREAD= IUNIT(1)
      IQPRNT= IUNIT(2)
      CALL UCOPY (IUNIT(3),IQPNCH,3)

      JSET = IUCOMP (LAST(1),LETSET(1),3)
      IF (JSET.GE.2)  IQPRNT=IQLOG
      IQPR2 = IQPRNT
      IQLOG = IQPRNT
      CALL VFILL (IQDLUN,4,IQPRNT)
      NQUSED= 0

      CALL VZERO  (IQDATE,7)
      CALL VBLANK (IQHEAD,20)
      CALL DATIME (IQDATE,IQTIME)


      LQADR = LOCF (LQ(1))
      LQADR2= LQADR - 2
      NQSYSS= LOCF (LQWM) - LQADR
      NQSYSL= LOCF (USER) - LQADR
      NQMAX = LOCF (LAST) - LQADR
      NQAUGM(2) = NQMAX
      NQSYSR= NQSYSL

      LQEND = NQMAX
      LQFIX = LQEND
      LQSTA = LQEND
      LQTOL = LQSTA - NQMEM
      NQLINK= NQSYSL
      LQWORG= NQSYSL + 1
      LQWORK= LQWORG

      I = LOCF(LQMAIN) - LQADR
      N = NQSYSS - I
      DO 24 J=1,N
   24 KVECT(J)= J+I
      CALL VZERO (QUEST,50)
      CALL VZERO (Q,NQSYSL)


      QVERSN = 3.47





C--                TEST VALIDITY OF QFATAL
      NQINIT= 0
      RETURN
      END
