CDECK  ID>, PABERR.
      SUBROUTINE PABERR (LUN)

C-    ABNORMAL STOP ON READ ERROR

      COMMON /QUNIT/ IQREAD,IQPRNT,IQPR2,IQLOG,IQPNCH,IQTTIN,IQTYPE
     +,              IQDLUN,IQFLUN,IQHLUN,IQCLUN,  NQUSED


      WRITE (IQPRNT,9000) LUN
      CALL PABEND

 9000 FORMAT (1X/' *****    READ ERROR ON LUN=',I4)
      END
