CDECK  ID>, PINIT.
      SUBROUTINE PINIT

      COMMON /MQCMOV/NQSYSS
      COMMON /MQCM/         NQSYSR,NQSYSL,NQLINK,LQWORG,LQWORK,LQTOL
     +,              LQSTA,LQEND,LQFIX,NQMAX, NQRESV,NQMEM,LQADR,LQADR2
      COMMON /QUNIT/ IQREAD,IQPRNT,IQPR2,IQLOG,IQPNCH,IQTTIN,IQTYPE
     +,              IQDLUN,IQFLUN,IQHLUN,IQCLUN,  NQUSED
      COMMON /QHEADP/IQHEAD(20),IQDATE,IQTIME,IQPAGE,NQPAGE(4)
      PARAMETER      (IQBDRO=25, IQBMAR=26, IQBCRI=27, IQBSYS=31)
      COMMON /QBITS/ IQDROP,IQMARK,IQCRIT,IQZIM,IQZIP,IQSYS
                         DIMENSION    IQUEST(30)
                         DIMENSION                 LQ(99), IQ(99), Q(99)
                         EQUIVALENCE (QUEST,IQUEST),    (LQUSER,LQ,IQ,Q)
      COMMON //      QUEST(30),LQUSER(7),LQMAIN,LQSYS(24),LQPRIV(7)
     +,              LQ1,LQ2,LQ3,LQ4,LQ5,LQ6,LQ7,LQSV,LQAN,LQDW,LQUP
     +, KADRV(9), LEXD,LEXH,LEXP,LPAM,LDECO, LADRV(14)
     +, NVOPER(6),MOPTIO(31),JANSW,JCARD,NDECKR,NVUSEB(14),MEXDEC(6)
     +, NVINC(6),NVUTY(16),NVIMAT(6),NVACT(6),NVGARB(6),NVWARN(6)
     +, NVARRQ(6),NVARR(10),IDARRV(10),NVARRI(12),NVCCP(10)
     +, NVDEP(19),MDEPAR,NVDEPL(6),  MWK(80),MWKX(80)
     +,            ISPACE(160000),LAST
C--------------    END CDE                             --------------
      DATA  IISET  / 4HSET  /


      LAST  = IISET
      IQLOG = IQPRNT
      ISAVE = IQREAD

      CALL MQINIT (LAST)
      NQLINK = IQLOCF(NVOPER(1)) - 1
      LQWORG = IQLOCF(ISPACE(1))

      IQREAD = ISAVE

      LQWORK = LQWORG

      WRITE (IQPRNT,9000) IQDATE,IQTIME
 9000 FORMAT                                       (1X/10H VERSION  ,
     + 40HPATCHY  4.15 /1  911211 12.02                                     HOLD
     F,12H.RJP, TODAY:,I8,I6/1X)

      CALL VZERO  (LQ1,LQWORK)
      CALL PLOAD
      CALL PREADY
      RETURN
      END
