CDECK  ID>, QABEND.
      SUBROUTINE QABEND

C-    QABEND FOR PRODUCTION, NO LOADING OF QPOSTM

      COMMON /QUNIT/ IQREAD,IQPRNT,IQPR2,IQLOG,IQPNCH,IQTTIN,IQTYPE
     +,              IQDLUN,IQFLUN,IQHLUN,IQCLUN,  NQUSED

      WRITE (IQPRNT,9000)
      CALL PABEND

 9000 FORMAT (1X/' EXIT VIA QFATAL.')
      END
