CDECK  ID>, QFATAM.
      SUBROUTINE QFATAM (NAME)

      COMMON       /SLATE/ MMD(10), M(30)
      COMMON /QBCD/  IQNUM2(11),IQLETT(26),IQNUM(10),IQPLUS
     +,              IQMINS,IQSTAR,IQSLAS,IQOPEN,IQCLOS,IQDOLL,IQEQU
     +,              IQBLAN,IQCOMA,IQDOT,IQAPO,  IQCROS
      COMMON /QSTATE/QVERSN,NQINIT,NQSTAG(2),NQPHAS,NQERR,QDEBUG,NQDCUT
     +,              NQNEWB,NQAFTB,NQM99,NQLOWB,NQWCUT,NQLOCK,QSTDUM
     +,              NQAUGM(2),NQZIP(8),AQMEM(12)
                         INTEGER QDEBUG
      COMMON /QUNIT/ IQREAD,IQPRNT,IQPR2,IQLOG,IQPNCH,IQTTIN,IQTYPE
     +,              IQDLUN,IQFLUN,IQHLUN,IQCLUN,  NQUSED
C--------------    END CDE                             -----------------  ------
      DIMENSION    NAME(9)
      DATA  INIT   /4HINIT /


      IF (NQERR.NE.0)  GO TO 19
      NQERR = NQERR+1

      CALL UCTOH1 (NAME,M,30)
      N =  IUFIND (IQDOT,M,1,29)
      WRITE (IQLOG,9001) (M(J),J=1,N)

      NQERR = 0
   19 CALL QFATAL

 9001 FORMAT (1H-,3(/10X,30(1H*)),24H    QFATAL REACHED FROM ,30A1)
      END
