CDECK  ID>, QFATAL.
      SUBROUTINE QFATAL

      COMMON /QSTATE/QVERSN,NQINIT,NQSTAG(2),NQPHAS,NQERR,QDEBUG,NQDCUT
     +,              NQNEWB,NQAFTB,NQM99,NQLOWB,NQWCUT,NQLOCK,QSTDUM
     +,              NQAUGM(2),NQZIP(8),AQMEM(12)
                         INTEGER QDEBUG
      COMMON /QUNIT/ IQREAD,IQPRNT,IQPR2,IQLOG,IQPNCH,IQTTIN,IQTYPE
     +,              IQDLUN,IQFLUN,IQHLUN,IQCLUN,  NQUSED
C--------------    END CDE                             -----------------  ------
      DATA  INIT   /4HINIT /


      IF (NQERR.NE.0)  GO TO 19
      NQERR = NQERR+1
      IF (IQTYPE.NE.0)  WRITE (IQTYPE,9009)
 9009 FORMAT (16H QFATAL REACHED.)
      CALL QABEND

C----              RECOVERY LOOP

   19 NQERR = NQERR + 1
      IF (NQERR.LT.4)  WRITE (IQLOG,9019)
      CALL ABEND

 9019 FORMAT (29H0STOP FOR RE-ENTRY TO QFATAL.)
      END
