CDECK  ID>, QLUMPR.
      SUBROUTINE QLUMPR (NW)

C-    SHORTEN BANK IN /QCN/ TO NW WORDS

      PARAMETER      (NQFNAE=2, NQFNAD=1, NQFNAU=3)
      PARAMETER      (IQFSTR=19, NQFSTR=6,  IQFSYS=25, NQFSYS=8)
      COMMON /MQCF/  NQNAME,NQNAMD,NQNAMU, IQSTRU,NQSTRU, IQSYSB,NQSYSB
      COMMON /MQCMOV/NQSYSS
      COMMON /MQCM/         NQSYSR,NQSYSL,NQLINK,LQWORG,LQWORK,LQTOL
     +,              LQSTA,LQEND,LQFIX,NQMAX, NQRESV,NQMEM,LQADR,LQADR2
      COMMON /QCN/   IQLS,IQID,IQNL,IQNS,IQND,IQFOUL
      PARAMETER      (IQBITW=32, IQBITC=8, IQCHAW=4)
      COMMON /QMACH/ NQBITW,NQCHAW,NQLNOR,NQLMAX,NQLPTH,NQRMAX,QLPCT
     +,              NQOCT(3),NQHEX(3),NQOCTD(3)
      PARAMETER      (IQBDRO=25, IQBMAR=26, IQBCRI=27, IQBSYS=31)
      COMMON /QBITS/ IQDROP,IQMARK,IQCRIT,IQZIM,IQZIP,IQSYS
                         DIMENSION    IQUEST(30)
                         DIMENSION                 LQ(99), IQ(99), Q(99)
                         EQUIVALENCE (QUEST,IQUEST),    (LQUSER,LQ,IQ,Q)
      COMMON //      QUEST(30),LQUSER(7),LQMAIN,LQSYS(24),LQPRIV(7)
     +,              LQ1,LQ2,LQ3,LQ4,LQ5,LQ6,LQ7,LQSV,LQAN,LQDW,LQUP
C--------------    END CDE                             -----------------  ------
      DIMENSION    NW(9)

      N   = NW(1)
      NCUT= IQND - N
      IF (NCUT.LE.0)         RETURN
      L   = IQLS + N + 1

      IF (IQLS+IQND+1.EQ.LQWORK)  GO TO 41
      IF (NCUT.LT.NQNAMU)         RETURN
      LQ(L)   = IQID
      LQ(L+1) = NCUT - NQNAMU
      LQ(L+2) = 0
      CALL SBIT1 (LQ(L+1),NQBITW)
      CALL SBIT1 (LQ(L+2),IQDROP)
      GO TO 44

   41 LQWORK = L
   44 CALL SBYT (N,LQ(IQLS-IQNL-1),1,15)
      RETURN
      END
