CDECK  ID>, QPAGE.
      SUBROUTINE QPAGE (LUN,LINES,JAUTO)

      PARAMETER      (IQBITW=32, IQBITC=8, IQCHAW=4)
      COMMON /QMACH/ NQBITW,NQCHAW,NQLNOR,NQLMAX,NQLPTH,NQRMAX,QLPCT
     +,              NQOCT(3),NQHEX(3),NQOCTD(3)
      COMMON /QUNIT/ IQREAD,IQPRNT,IQPR2,IQLOG,IQPNCH,IQTTIN,IQTYPE
     +,              IQDLUN,IQFLUN,IQHLUN,IQCLUN,  NQUSED
      COMMON /QHEADP/IQHEAD(20),IQDATE,IQTIME,IQPAGE,NQPAGE(4)
      PARAMETER      (IQBDRO=25, IQBMAR=26, IQBCRI=27, IQBSYS=31)
      COMMON /QBITS/ IQDROP,IQMARK,IQCRIT,IQZIM,IQZIP,IQSYS
                         DIMENSION    IQUEST(30)
                         DIMENSION                 LQ(99), IQ(99), Q(99)
                         EQUIVALENCE (QUEST,IQUEST),    (LQUSER,LQ,IQ,Q)
      COMMON //      QUEST(30),LQUSER(7),LQMAIN,LQSYS(24),LQPRIV(7)
     +,              LQ1,LQ2,LQ3,LQ4,LQ5,LQ6,LQ7,LQSV,LQAN,LQDW,LQUP
C--------------    END CDE                             -----------------  ------
      DIMENSION    LUNS(3)
      EQUIVALENCE (LUNS(1),IQPRNT)
      INTEGER      HEADER(23)
      EQUIVALENCE (HEADER(1),IQHEAD(1))


      IF (LINES.LT.0)  GO TO 11
      IQUEST(1)= 0
    7 IF (NQUSED.LE.NQLMAX)  GO TO 8
      NQUSED= NQUSED - NQLMAX
      GO TO 7
    8 IF (NQUSED+LINES.LE.NQLNOR)  RETURN

   11 IQUEST(1)= 1
      JLUN  = IUCOMP (LUN,LUNS,3) + 1
      IQPAGE= NQPAGE(JLUN) + 1
      NQPAGE(JLUN)= IQPAGE

      NQUSED= NQLPTH + 1
      WRITE (LUN,9000) HEADER
 9000 FORMAT (1H1,20A4,28X,I6,1H/,I4,6H  PAGE,I5)
      RETURN
      END
