CDECK  ID>, RQTELL.
      SUBROUTINE RQTELL (ID,NUM)

      COMMON /QUNIT/ IQREAD,IQPRNT,IQPR2,IQLOG,IQPNCH,IQTTIN,IQTYPE
     +,              IQDLUN,IQFLUN,IQHLUN,IQCLUN,  NQUSED

      WRITE (IQLOG,9000)  ID,NUM
      CALL PABEND

C9000 FORMAT ('0RQTELL REACHED WITH ',2O22)                              OCT
 9000 FORMAT ('0RQTELL REACHED WITH ',2Z10)                              HEX
      END
