CDECK  ID>, SETOPT.
      SUBROUTINE SETOPT

C-    UPDATE GLOBAL OPTIONS FROM CURRENT T-PARAMETER

      COMMON /QBCD/  IQNUM2(11),IQLETT(26),IQNUM(10),IQPLUS
     +,              IQMINS,IQSTAR,IQSLAS,IQOPEN,IQCLOS,IQDOLL,IQEQU
     +,              IQBLAN,IQCOMA,IQDOT,IQAPO,  IQCROS
      COMMON /QUNIT/ IQREAD,IQPRNT,IQPR2,IQLOG,IQPNCH,IQTTIN,IQTYPE
     +,              IQDLUN,IQFLUN,IQHLUN,IQCLUN,  NQUSED
      COMMON /CCPARA/NCHCCD,NCHCCT,KARDCC(84),   JCCTYP,JCCPRE,JCCEND
     +,              MCCPAR(120),NCCPAR,MXCCIF,JCCIFV,JCCBAD,JCCWK(4)
     +,              JCCPP,JCCPD,JCCPZ,JCCPT,JCCPIF,JCCPC,JCCPN
     +,              NCCPP,NCCPD,NCCPZ,NCCPT,NCCPIF,NCCPC,NCCPN
      COMMON /IOFCOM/IOTALL,IOTOFF,IOTON,IOSPEC,IOPARF(5),IOMODE(12)
      PARAMETER      (IQBDRO=25, IQBMAR=26, IQBCRI=27, IQBSYS=31)
      COMMON /QBITS/ IQDROP,IQMARK,IQCRIT,IQZIM,IQZIP,IQSYS
                         DIMENSION    IQUEST(30)
                         DIMENSION                 LQ(99), IQ(99), Q(99)
                         EQUIVALENCE (QUEST,IQUEST),    (LQUSER,LQ,IQ,Q)
      COMMON //      QUEST(30),LQUSER(7),LQMAIN,LQSYS(24),LQPRIV(7)
     +,              LQ1,LQ2,LQ3,LQ4,LQ5,LQ6,LQ7,LQSV,LQAN,LQDW,LQUP
     +, KADRV(9), LEXD,LEXH,LEXP,LPAM,LDECO, LADRV(14)
     +, NVOPER(6),MOPTIO(31),JANSW,JCARD,NDECKR,NVUSEB(14),MEXDEC(6)
     +, NVINC(6),NVUTY(16),NVIMAT(6),NVACT(6),NVGARB(6),NVWARN(6)
     +, NVARRQ(6),NVARR(10),IDARRV(10),NVARRI(12),NVCCP(10)
     +, NVDEP(19),MDEPAR,NVDEPL(6),  MWK(80),MWKX(80)
C--------------    END CDE                             -----------------  ------



      MTYP = JBYT (MCCPAR(JCCPT+1),1,30)
      CALL SBYTOR (MTYP,MOPTIO(31),1,30)                                -MSK
C     MOPTIO(31) = MOPTIO(31) .OR. MTYP                                  MSKC
      IF (JBIT(MTYP,15)   .EQ.0)   GO TO 31                             -MSK
C     IF ((MTYP.AND.16384).EQ.0)   GO TO 31                              MSKC

C--                CANCEL OPTION

      MOPTIO(31) = MOPTIO(31) - MTYP

C--                UNRAVEL

   31 IOTALL = IOTYPE (MOPTIO(31),5)
      CALL UPKBYT (MOPTIO(31),1,MOPTIO(1),30,0)

      DO 79  J=1,30
      IQUEST(J)= IQDOT
      IF (MOPTIO(J).NE.0)  IQUEST(J)=IQLETT(J)
   79 CONTINUE
      WRITE (IQPRNT,9079) IQUEST
      NQUSED = NQUSED + 2
      RETURN

 9079 FORMAT (20X,8HOPTIONS ,30A1/1X)
      END
