CDECK  ID>, YBINEX.
      SUBROUTINE YBINEX

C-         CONVERT CARD-PAM TO COMPACT BINARY FORMAT

      COMMON /QBCD/  IQNUM2(11),IQLETT(26),IQNUM(10),IQPLUS
     +,              IQMINS,IQSTAR,IQSLAS,IQOPEN,IQCLOS,IQDOLL,IQEQU
     +,              IQBLAN,IQCOMA,IQDOT,IQAPO,  IQCROS
      COMMON /QUNIT/ IQREAD,IQPRNT,IQPR2,IQLOG,IQPNCH,IQTTIN,IQTYPE
     +,              IQDLUN,IQFLUN,IQHLUN,IQCLUN,  NQUSED
      COMMON /ARRCOM/LUNPAM,NCHKD,NWKD,NCARDP,NAREOF,NSKIPR,KDHOLD(20)
     +,              NTRUNC,IPROMU,IPROMI
      COMMON /CCPARA/NCHCCD,NCHCCT,KARDCC(84),   JCCTYP,JCCPRE,JCCEND
     +,              MCCPAR(120),NCCPAR,MXCCIF,JCCIFV,JCCBAD,JCCWK(4)
     +,              JCCPP,JCCPD,JCCPZ,JCCPT,JCCPIF,JCCPC,JCCPN
     +,              NCCPP,NCCPD,NCCPZ,NCCPT,NCCPIF,NCCPC,NCCPN
      COMMON /CCPARU/MCCTOU,JCCLOW,JCCTPX
      COMMON /CCTYPE/MCCQUI,MCCPAM,MCCTIT,MCCPAT,MCCDEC,MCCDEF,MCCEOD
     +,              MCCASM,MCCOPT,MCCUSE
      COMMON /IOFCOM/IOTALL,IOTOFF,IOTON,IOSPEC,IOPARF(5),IOMODE(12)
      PARAMETER      (KDNWT=20, KDNWT1=19,KDNCHW=4, KDBITS=8)
      PARAMETER      (KDPOST=25,KDBLIN=32,KDMARK=0, KDSUB=63,JPOSIG=1)
      COMMON /KDPKCM/KDBLAN,KDEOD(2)
      PARAMETER      (IQBDRO=25, IQBMAR=26, IQBCRI=27, IQBSYS=31)
      COMMON /QBITS/ IQDROP,IQMARK,IQCRIT,IQZIM,IQZIP,IQSYS
                         DIMENSION    IQUEST(30)
                         DIMENSION                 LQ(99), IQ(99), Q(99)
                         EQUIVALENCE (QUEST,IQUEST),    (LQUSER,LQ,IQ,Q)
      COMMON //      QUEST(30),LQUSER(7),LQMAIN,LQSYS(24),LQPRIV(7)
     +,              LQ1,LQ2,LQ3,LQ4,LQ5,LQ6,LQ7,LQSV,LQAN,LQDW,LQUP
     +, KADRV(14),LADRV(11),LCCIX,LBUF,LLAST
     +, NVOPER(6),MOPTIO(31),JANSW,JCARD,NDECKR,NVUSEX(20)
     +, NVINC(6),NVUTY(17),IDEOF(9),NVPROX(6),LOGLVG,LOGLEV,NVWARX(6)
     +, NVOLDQ(4),MVOLD1,MVOLDN,  NVOLD(7),NRTOLD,NROLD,MAXEOF
     +, IDOLDV(8),JPDOLD,JOLD, NVARRI(9),LARX,LARXE,LINBIN, NVCCP(10)
     +, NVNEW(7),NRTNEW,NRNEW,LLASTN, IDNEWV(8),JPDNEW,NDKNEW
     +, NVNEWL(3),NCDECK,JNEW,MODEPR,  MWK(80),MWKX(80)
      DIMENSION      IDD(2),             IDP(2),             IDF(2)
      EQUIVALENCE
     +       (IDD(1),IDNEWV(1)), (IDP(1),IDNEWV(3)), (IDF(1),IDNEWV(5))
C--------------    END CDE                             -----------------  ------
      DATA  MMPAM  /4HPAM /


C----              INITIALISE
C-    1 ATT, 2 RES, 4 CARD, 8 DET, 16 EOF, 32 HOLD, 64 OUT, 256 I, 512 F

      CALL AUXFIL (260,NVOLD(1),5HCARDS)
      NVNEW(6) = MMPAM

      MODEPR = IQPLUS
      NDISCD = 0
      NTRUNC = 80 - 8*MOPTIO(20)
      MCCTOU = 7

C----              START NEW FILE

   10 NCARDP = 0
      JPDNEW = 3
      JCCTYP = 99

      CALL KDNEXT (KDHOLD(1))
      IF (NCHKD.LT.0)        GO TO 96
      IF (NROLD.NE.0)  CALL AUXFIL (0,NVOLD(1),0)
      GO TO 41

C----              HUNTING FOR START OF NEW DECK

   20 NDISCD = NDISCD + 1
   21 CALL KDNEXT(KDHOLD(1))
      IF (NCHKD.LT.0)        GO TO 90

      JCCTYP = JARTPX (KDHOLD(1))
      IF (JCCTYP -  MCCTIT)  20,91,22
   22 IF (JCCTYP.GE.MCCEOD)  GO TO 20

      CALL CCKRAK (KDHOLD(1))
      IF (JCCBAD.NE.0)       GO TO 70
      IF (JCCTYP.GE.MCCEOD)  GO TO 20
      GO TO 44

C----              NORMAL LOOP FOR DECKS

   41 CALL PILEUP
      IF (NCHKD)             91,21,44

   44 JPDNEW = MCCDEF - JCCTYP
      IF (JPDNEW.NE.3)       GO TO 41
      GO TO 91


C----      BAD C/C, SKIP THIS CARD

   70 JC = NCARDP - NCDECK
      WRITE (IQPRNT,9058) IDP,IDD,JC,(KARDCC(J),J=1,NCHCCT)
      NVWARX(1) = NVWARX(1) + 1
      GO TO 20

C--        END OF FILE ON LUNPAM

   90 IF (NCHKD.EQ. -1)      GO TO 21
   91 IF (NCARDP.EQ.0)       GO TO 96
      NROLD = NCARDP
      IF (NCHKD.GE. -2)      GO TO 10

C--                EOI

   96 CALL AUXFIL (512,NVOLD(1),0)
      CALL POPREW
      IF (NDISCD+NVWARX(1).NE.0)  WRITE (IQPRNT,9098) NDISCD,NVWARX(1)
      RETURN

C9058 FORMAT (3H0P=,A8,   3H D=,A8,   3H C=,I6,16H *** FAULTY C/C ,72A1) A8M
C9058 FORMAT (3H0P=,A6,A2,3H D=,A6,A2,3H C=,I6,16H *** FAULTY C/C ,72A1) A6
C9058 FORMAT (3H0P=,A5,A3,3H D=,A5,A3,3H C=,I6,16H *** FAULTY C/C ,72A1) A5
 9058 FORMAT (3H0P=,2A4,  3H D=,2A4,  3H C=,I6,16H *** FAULTY C/C ,72A1) A4
 9098 FORMAT (1X,3(/1X,20(1H*)),I5,' CARDS BETWEEN DECKS HAVE BEEN IGNOR
     FED,'/21X,I5,' BAD CONTROL CARDS HAVE BEEN SEEN.')
      END
