CDECK  ID>, YEDXCH.
      SUBROUTINE YEDXCH (JLUNP)

C-    SWOP ACTIVE UNITS  NEW  OR  OLD

      COMMON /QUNIT/ IQREAD,IQPRNT,IQPR2,IQLOG,IQPNCH,IQTTIN,IQTYPE
     +,              IQDLUN,IQFLUN,IQHLUN,IQCLUN,  NQUSED
      PARAMETER      (IQBDRO=25, IQBMAR=26, IQBCRI=27, IQBSYS=31)
      COMMON /QBITS/ IQDROP,IQMARK,IQCRIT,IQZIM,IQZIP,IQSYS
                         DIMENSION    IQUEST(30)
                         DIMENSION                 LQ(99), IQ(99), Q(99)
                         EQUIVALENCE (QUEST,IQUEST),    (LQUSER,LQ,IQ,Q)
      COMMON //      QUEST(30),LQUSER(7),LQMAIN,LQSYS(24),LQPRIV(7)
     +,              LQ1,LQ2,LQ3,LQ4,LQ5,LQ6,LQ7,LQSV,LQAN,LQDW,LQUP
     +, KADRV(14),LADRV(11),LCCIX,LBUF,LLAST
     +, NVOPER(6),MOPTIO(31),JANSW,JCARD,NDECKR,NVUSEX(20)
     +, NVINC(6),NVUTY(17),IDEOF(9),NVPROX(6),LOGLVG,LOGLEV,NVWARX(6)
     +, NVOLDQ(4),MVOLD1,MVOLDN,  NVOLD(7),NRTOLD,NROLD,MAXEOF
     +, IDOLDV(8),JPDOLD,JOLD, NVARRI(9),LARX,LARXE,LINBIN, NVCCP(10)
     +, NVNEW(7),NRTNEW,NRNEW,LLASTN, IDNEWV(8),JPDNEW,NDKNEW
     +, NVNEWL(3),NCDECK,JNEW,MODEPR,  MWK(80),MWKX(80)
C--------------    END CDE                             -----------------  ------
      DIMENSION    JLUNP(9)
      EQUIVALENCE (LSVARE,LADRV(9))


      JLUN = JLUNP(1)
      NWSV = IQ(LSVARE+1)
      IF  (JLUN.GE.4)        GO TO 31

      IF (JLUN.EQ.JOLD)      RETURN
      L = IQ(LSVARE-JOLD)
      CALL UCOPY (NVOLD(1),IQ(L),NWSV)
      L = IQ(LSVARE-JLUN)
      CALL UCOPY (IQ(L),NVOLD(1),NWSV)
      NWSV = NVOLD(6)
      GO TO 37

   31 IF (JLUN.EQ.JNEW+3)    RETURN
      LLASTN= LLAST
      L = IQ(LSVARE-JNEW-3)
      CALL UCOPY (NVNEW(1),IQ(L),NWSV)
      L = IQ(LSVARE-JLUN)
      CALL UCOPY (IQ(L),NVNEW(1),NWSV)
      LLAST = LLASTN
      JNEW  = JLUN - 3
      NWSV  = NVNEW(6)
   37 IF (LOGLEV.LT.1)       RETURN
      WRITE (IQPRNT,9037) NWSV
      RETURN

 9037 FORMAT (9H ACTIVE ',A4,1H')
      END
