CDECK  ID>, YLISPG.
      SUBROUTINE YLISPG

C-    PRINT  PAGE / DECK  HEADER LINE

      PARAMETER      (IQBITW=32, IQBITC=8, IQCHAW=4)
      COMMON /QMACH/ NQBITW,NQCHAW,NQLNOR,NQLMAX,NQLPTH,NQRMAX,QLPCT
     +,              NQOCT(3),NQHEX(3),NQOCTD(3)
      COMMON /QUNIT/ IQREAD,IQPRNT,IQPR2,IQLOG,IQPNCH,IQTTIN,IQTYPE
     +,              IQDLUN,IQFLUN,IQHLUN,IQCLUN,  NQUSED
      COMMON /QHEADP/IQHEAD(20),IQDATE,IQTIME,IQPAGE,NQPAGE(4)
      COMMON /CCPARA/NCHCCD,NCHCCT,KARDCC(84),   JCCTYP,JCCPRE,JCCEND
     +,              MCCPAR(120),NCCPAR,MXCCIF,JCCIFV,JCCBAD,JCCWK(4)
     +,              JCCPP,JCCPD,JCCPZ,JCCPT,JCCPIF,JCCPC,JCCPN
     +,              NCCPP,NCCPD,NCCPZ,NCCPT,NCCPIF,NCCPC,NCCPN
      PARAMETER      (IQBDRO=25, IQBMAR=26, IQBCRI=27, IQBSYS=31)
      COMMON /QBITS/ IQDROP,IQMARK,IQCRIT,IQZIM,IQZIP,IQSYS
                         DIMENSION    IQUEST(30)
                         DIMENSION                 LQ(99), IQ(99), Q(99)
                         EQUIVALENCE (QUEST,IQUEST),    (LQUSER,LQ,IQ,Q)
      COMMON //      QUEST(30),LQUSER(7),LQMAIN,LQSYS(24),LQPRIV(7)
     +,              LQ1,LQ2,LQ3,LQ4,LQ5,LQ6,LQ7,LQSV,LQAN,LQDW,LQUP
     +, KADRV(14),LADRV(11),LCCIX,LBUF,LLAST
     +, NVOPER(6),MOPTIO(31),JANSW,JCARD,NDECKR,NVUSEX(20)
     +, NVINC(6),NVUTY(17),IDEOF(9),NVPROX(6),LOGLVG,LOGLEV,NVWARX(6)
     +, NVOLDQ(4),MVOLD1,MVOLDN,  NVOLD(7),NRTOLD,NROLD,MAXEOF
     +, IDOLDV(8),JPDOLD,JOLD, NVARRI(9),LARX,LARXE,LINBIN, NVCCP(10)
     +, NVNEW(10), IDNEWV(10), NVNEWL(6),  MWK(80),MWKX(80)
      DIMENSION      IDD(2),             IDP(2),             IDF(2)
      EQUIVALENCE
     +       (IDD(1),IDOLDV(1)), (IDP(1),IDOLDV(3)), (IDF(1),IDOLDV(5))
C--------------    END CDE                             -----------------  ------


 9001 FORMAT                (1H1,I4,61X,3H P=,2A4,3H D=,2A4,1X,I2,
     F21X,4HPAGE,I4/1X)
 9002 FORMAT (1X/1X,I4,A5,A4,2X,50(1H=),3H P=,2A4,3H D=,2A4,4H  1 ,
     F28(1H=)/1X)
 9003 FORMAT   (1H1,I4,A5,A4,2X,50(1H=),3H P=,2A4,3H D=,2A4,4H  1 ,
     F19(1H=),5H PAGE,I4/1X)


C--------          NEW PAGE, NOT FIRST OF CURRENT DECK

      IF (JCARD.EQ.0)        GO TO 31
      NQPAGE(2) = NQPAGE(2) + 1
      WRITE (IQPRNT,9001) NDECKR,IDP,IDD,IQPAGE,NQPAGE(2)
      IQPAGE = IQPAGE + 1
      NQUSED = NQLPTH + 2
      RETURN

C--------          START OF NEW DECK, PAGE OPTION ON

   31 IF (MOPTIO(19).EQ.0)     GO TO 41
      IF (JBIT(MCCPAR(JCCPT+1),10) .NE.0)  GO TO 70                     -MSK
C     IF ((MCCPAR(JCCPT+1).AND.512).NE.0)  GO TO 70                      MSKC
      IF (NVARRI(1).NE.1)      GO TO 74
      IF (NVCCP(1) .GE.6)      GO TO 74
      IF (NQUSED.GE.NQLPTH+7)  GO TO 74
      IF (JBIT(MCCPAR(JCCPT+1),5) .EQ.0)   GO TO 71                     -MSK
C     IF ((MCCPAR(JCCPT+1).AND.16).EQ.0)   GO TO 71                      MSKC
      GO TO 74

C--------          START OF NEW DECK, PAGE OPTION OFF

   41 CONTINUE

C--                PAGE 1 WITHOUT EJECT

   70 IF (NQUSED+6.GE.NQLNOR)  GO TO 74
   71 WRITE (IQPRNT,9002) NDECKR,IDF,IDP,IDD
      NQUSED = NQUSED + 3
      IQPAGE = 2
      RETURN

C--                PAGE 1 WITH EJECT

   74 NQPAGE(2) = NQPAGE(2) + 1
      WRITE (IQPRNT,9003) NDECKR,IDF,IDP,IDD,NQPAGE(2)
      NQUSED = NQLPTH + 2
      IQPAGE = 2
      RETURN
      END
