CDECK  ID>, YSHMAC.
      SUBROUTINE YSHMAC (ID,NCHP,MACRO)

C-    LOAD AND PRINT 1 MACRO

      COMMON /QBCD/  IQNUM2(11),IQLETT(26),IQNUM(10),IQPLUS
     +,              IQMINS,IQSTAR,IQSLAS,IQOPEN,IQCLOS,IQDOLL,IQEQU
     +,              IQBLAN,IQCOMA,IQDOT,IQAPO,  IQCROS
      COMMON /QUNIT/ IQREAD,IQPRNT,IQPR2,IQLOG,IQPNCH,IQTTIN,IQTYPE
     +,              IQDLUN,IQFLUN,IQHLUN,IQCLUN,  NQUSED
      PARAMETER      (IQBITW=32, IQBITC=8, IQCHAW=4)
      COMMON /QMACH/ NQBITW,NQCHAW,NQLNOR,NQLMAX,NQLPTH,NQRMAX,QLPCT
     +,              NQOCT(3),NQHEX(3),NQOCTD(3)
      PARAMETER      (IQBDRO=25, IQBMAR=26, IQBCRI=27, IQBSYS=31)
      COMMON /QBITS/ IQDROP,IQMARK,IQCRIT,IQZIM,IQZIP,IQSYS
                         DIMENSION    IQUEST(30)
                         DIMENSION                 LQ(99), IQ(99), Q(99)
                         EQUIVALENCE (QUEST,IQUEST),    (LQUSER,LQ,IQ,Q)
      COMMON //      QUEST(30),LQUSER(7),LQMAIN,LQSYS(24),LQPRIV(7)
     +,              LQ1,LQ2,LQ3,LQ4,LQ5,LQ6,LQ7,LQSV,LQAN,LQDW,LQUP
     +, KADRV(14),LADRV(11),LCCIX,LBUF,LLAST
     +, NVOPER(6),MOPTIO(31),JANSW,JCARD,NDECKR,NVUSEX(20)
     +, NVINC(6),NVUTY(17),IDEOF(9),NVPROX(6),LOGLVG,LOGLEV,NVWARX(6)
     +, NVOLDQ(6), NVOLD(10), IDOLDV(10), NVARRI(12), NVCCP(10)
     +, NVNEW(10), IDNEWV(10), NVNEWL(6),  MWK(80),MWKX(80)
C--------------    END CDE                             --------------
      DIMENSION    ID(2), NCHP(9)
      CHARACTER    MACRO*(*)
      DIMENSION    MNAMES(4)
      DATA         MNAMES /4HMAC ,1,1,2H** /


      NCH       = NCHP(1)
      NWORDS    = (NCH-1) / IQCHAW + 1
      MNAMES(4) = NWORDS + 3
      CALL LIFTBK (LSMAC,1,0,MNAMES(1),0)
      CALL UBLOW  (ID(1),MWKX(1),8)
      J = IUFIND (IQBLAN,MWKX(1),1,8)
      CALL VBLANK (MWKX(J),8)
      CALL UBUNCH (MWKX(1),IQ(LSMAC+1),8)
      IQ(LSMAC+3) = NCH
      CALL UCTOH1 (MACRO,MWK(1),NCH)
      CALL UBUNCH (MWK(1),IQ(LSMAC+4),NCH)
      IF (LOGLEV.LT.2)       RETURN
      WRITE (IQPRNT,9001) (MWKX(J),J=1,8), (MWK(J),J=1,NCH)
      RETURN

 9001 FORMAT (5H ID= ,8A1,7H TEXT= ,80A1)
      END
