CDECK  ID>, YSHTAG.
      SUBROUTINE YSHTAG

C-    PROCESS CARDS UNTIL INCL. NEXT TAGGED CARD

      COMMON /QBCD/  IQNUM2(11),IQLETT(26),IQNUM(10),IQPLUS
     +,              IQMINS,IQSTAR,IQSLAS,IQOPEN,IQCLOS,IQDOLL,IQEQU
     +,              IQBLAN,IQCOMA,IQDOT,IQAPO,  IQCROS
      PARAMETER      (IQBITW=32, IQBITC=8, IQCHAW=4)
      COMMON /QMACH/ NQBITW,NQCHAW,NQLNOR,NQLMAX,NQLPTH,NQRMAX,QLPCT
     +,              NQOCT(3),NQHEX(3),NQOCTD(3)
      COMMON /ARRCOM/LUNPAM,NCHKD,NWKD,NCARDP,NAREOF,NSKIPR,KDHOLD(20)
     +,              NTRUNC,IPROMU,IPROMI
      COMMON /CCPARA/NCHCCD,NCHCCT,KARDCC(84),   JCCTYP,JCCPRE,JCCEND
     +,              MCCPAR(120),NCCPAR,MXCCIF,JCCIFV,JCCBAD,JCCWK(4)
     +,              JCCPP,JCCPD,JCCPZ,JCCPT,JCCPIF,JCCPC,JCCPN
     +,              NCCPP,NCCPD,NCCPZ,NCCPT,NCCPIF,NCCPC,NCCPN
      COMMON /DPLINE/LTK,NWTK, KIMAPR(3), KIMA(20), KIMAPS(9)
      PARAMETER      (KDNWT=20, KDNWT1=19,KDNCHW=4, KDBITS=8)
      PARAMETER      (KDPOST=25,KDBLIN=32,KDMARK=0, KDSUB=63,JPOSIG=1)
      COMMON /KDPKCM/KDBLAN,KDEOD(2)
      PARAMETER      (IQBDRO=25, IQBMAR=26, IQBCRI=27, IQBSYS=31)
      COMMON /QBITS/ IQDROP,IQMARK,IQCRIT,IQZIM,IQZIP,IQSYS
                         DIMENSION    IQUEST(30)
                         DIMENSION                 LQ(99), IQ(99), Q(99)
                         EQUIVALENCE (QUEST,IQUEST),    (LQUSER,LQ,IQ,Q)
      COMMON //      QUEST(30),LQUSER(7),LQMAIN,LQSYS(24),LQPRIV(7)
     +,              LQ1,LQ2,LQ3,LQ4,LQ5,LQ6,LQ7,LQSV,LQAN,LQDW,LQUP
     +, KADRV(14),LADRV(11),LCCIX,LBUF,LLAST
     +, NVOPER(6),MOPTIO(31),JANSW,JCARD,NDECKR,NVUSEX(20)
     +, NVINC(6),NVUTY(17),IDEOF(9),NVPROX(6),LOGLVG,LOGLEV,NVWARX(6)
     +, NVOLDQ(6), NVOLD(10), IDOLDV(10), NVARRI(12), NVCCP(10)
     +, NVNEW(10), IDNEWV(10), NVNEWL(6),  MWK(80),MWKX(80)
     +,    NINDX,NTOTCC,LEV,NCHTAG,NWWTAG, KD1ORG,KD1REP
     +,    MTAG(8),JTERM,NACCU,JTG,NEND
C--------------    END CDE                             -----------------  ------



      NCHTAG = -7
      NWTK  = 0

C--                READY NEXT CARD

   11 LTK = LTK + NWTK
      JCARD = JCARD + 1
      IF (JCARD.GE.NTOTCC)   RETURN
      LE = LTK + KDNWT1 - 1
      DO 13 L=LTK,LE
      IF (AND(IQ(L),Z'FF000000').EQ.0)    GO TO 14
   13 CONTINUE
      NWTK   = KDNWT
      NCHCCT = 80
      GO TO 22

   14 NWTK   = L - LTK + 1
      IF (NWTK.GE.NWWTAG)    GO TO 21
      IF (NWTK.NE.1)         GO TO 11
      IF (IQ(LTK).NE.KD1ORG) GO TO 11
      IQ(LTK) = KD1REP
      GO TO 11

   21 NCHCCT = NWTK * IQCHAW - 1
   22 CALL UBLOW (IQ(LTK),KARDCC(1),NCHCCT)
      IF (KARDCC(73).NE.IQBLAN)  GO TO 24
      IF (KARDCC(74).EQ.IQBLAN)  GO TO 11

   24 NEND = 0
      DO 28 J = 73,NCHCCT
      IF (KARDCC(J).EQ.IQBLAN)  GO TO 28
      NEND       = NEND + 1
      MTAG(NEND) = KARDCC(J)
   28 CONTINUE

      IF (NEND.NE.8)         GO TO 31
      DO 29 J = 2,8
      IF (MTAG(J).NE.MTAG(1))  GO TO 31
   29 CONTINUE
      GO TO 11

C--------- TAG COMBINATION LOGIC

   31 JTG   = 0
   32 NACCU = 0
   33 JTG   = JTG + 1

   34 CALL YSHVAL
      IF (JTERM)             71,36,38

C--        TERMINATOR IS  'PLUS'

   36 IF (NACCU.EQ.0)        GO TO 44
      GO TO 32

C--        TERMINATOR IS  'COMMA' , 'MINUS' OR 'END OF CARD'

   38 IF (JTERM - 2)         34,33,41

C--------- END OF CARD SEEN,   DECIDE

   41 IF (NACCU.EQ.0)        GO TO 44

C--        ACCEPT CARD

      KARDCC(1) = IQBLAN
      GO TO 48

C--        REJECT CARD

   44 KARDCC(1) = IQLETT(3)

   48 CALL UBUNCH(KARDCC(1),IQ(LTK),IQCHAW)
      IF (MOPTIO(1).EQ.0)    GO TO 11
      NCHTAG = 0
      LTK = LTK + NWTK
      RETURN

C--        UNKNOWN TAG

   71 IF (MOPTIO(21).EQ.0)   GO TO 11
      NCHTAG = 7
      LTK = LTK + NWTK
      RETURN
      END
