CDECK  ID>, YTOCEX.
      SUBROUTINE YTOCEX

C-     UNPACK BINARY PAM FILE AND PACK TO CETA FILE

      COMMON /QBCD/  IQNUM2(11),IQLETT(26),IQNUM(10),IQPLUS
     +,              IQMINS,IQSTAR,IQSLAS,IQOPEN,IQCLOS,IQDOLL,IQEQU
     +,              IQBLAN,IQCOMA,IQDOT,IQAPO,  IQCROS
      COMMON /QUNIT/ IQREAD,IQPRNT,IQPR2,IQLOG,IQPNCH,IQTTIN,IQTYPE
     +,              IQDLUN,IQFLUN,IQHLUN,IQCLUN,  NQUSED
      COMMON /ARRCOM/LUNPAM,NCHKD,NWKD,NCARDP,NAREOF,NSKIPR,KDHOLD(20)
     +,              NTRUNC,IPROMU,IPROMI
      COMMON /CCPARA/NCHCCD,NCHCCT,KARDCC(84),   JCCTYP,JCCPRE,JCCEND
     +,              MCCPAR(120),NCCPAR,MXCCIF,JCCIFV,JCCBAD,JCCWK(4)
     +,              JCCPP,JCCPD,JCCPZ,JCCPT,JCCPIF,JCCPC,JCCPN
     +,              NCCPP,NCCPD,NCCPZ,NCCPT,NCCPIF,NCCPC,NCCPN
      COMMON /CCPARU/MCCTOU,JCCLOW,JCCTPX
      COMMON /CCTYPE/MCCQUI,MCCPAM,MCCTIT,MCCPAT,MCCDEC,MCCDEF,MCCEOD
     +,              MCCASM,MCCOPT,MCCUSE
      COMMON /COMCET/INILEV,NWCEIN,NCHCEU,NWCEU
     +,              NWCEBA,IPAKCE(5),IPAKKD(5),JPOSA1,MXINHO
     +,              LCESAV(4)
      COMMON /DPLINE/LTK,NWTK, KIMAPR(3), KIMA(20), KIMAPS(9)
      COMMON /IOFCOM/IOTALL,IOTOFF,IOTON,IOSPEC,IOPARF(5),IOMODE(12)
      PARAMETER      (KDNWT=20, KDNWT1=19,KDNCHW=4, KDBITS=8)
      PARAMETER      (KDPOST=25,KDBLIN=32,KDMARK=0, KDSUB=63,JPOSIG=1)
      COMMON /KDPKCM/KDBLAN,KDEOD(2)
      PARAMETER      (IQBDRO=25, IQBMAR=26, IQBCRI=27, IQBSYS=31)
      COMMON /QBITS/ IQDROP,IQMARK,IQCRIT,IQZIM,IQZIP,IQSYS
                         DIMENSION    IQUEST(30)
                         DIMENSION                 LQ(99), IQ(99), Q(99)
                         EQUIVALENCE (QUEST,IQUEST),    (LQUSER,LQ,IQ,Q)
      COMMON //      QUEST(30),LQUSER(7),LQMAIN,LQSYS(24),LQPRIV(7)
     +,              LQ1,LQ2,LQ3,LQ4,LQ5,LQ6,LQ7,LQSV,LQAN,LQDW,LQUP
     +, KADRV(14),LADRV(11),LCCIX,LBUF,LLAST
     +, NVOPER(6),MOPTIO(31),JANSW,JCARD,NDECKR,NVUSEX(20)
     +, NVINC(6),NVUTY(17),IDEOF(9),NVPROX(6),LOGLVG,LOGLEV,NVWARX(6)
     +, NVOLDQ(4),MVOLD1,MVOLDN,  NVOLD(7),NRTOLD,NROLD,MAXEOF
     +, IDOLDV(8),JPDOLD,JOLD, NVARRI(9),LARX,LARXE,LINBIN, NVCCP(10)
     +, NVNEW(10), IDNEWV(10), NVNEWL(6),  MWK(80),MWKX(80)
C--------------    END CDE                             --------------
      EQUIVALENCE (JCCF,JCCPC)
      EQUIVALENCE (LUNEW,NVNEW(1))
      EQUIVALENCE (JMODDK,NVUTY(16))

      DIMENSION    NAME(8)
      EQUIVALENCE (NAME(1),IQUEST(1))

      DIMENSION    JOPINH(9), NOPINH(3)


C                   1---------  2----------  3---
C-                   A B  S  X   I  M  1  2   C
      DATA  JOPINH / 1,2,19,24,  9,13,28,29,  3   /
      DATA  NOPINH /         4,           8,  9   /



      CALL CETUP

      CALL SBIT0 (MOPTIO(31),3)
      CALL SBIT0 (MOPTIO(31),26)
      CALL SBIT0 (MOPTIO(31),19)

      JCCPT  = 0
      CALL SETOPT

      INILEV = 1

      JPAMCA = 0
      NSECTS = 0
      NSKIP  = 0
      IF (IQREAD.EQ.0)       GO TO 90

C-----             READ DATA CARDS

      LUNPAM = IQREAD
      NCHKD  = -1
      CALL KDNGO

   11 CONTINUE
      WRITE (IQPRNT,9011)
      MCCTOU = 7

   12 MOPTSV = MOPTIO(31)
      NCHKD  = -2
      CALL KDNEXT (KDHOLD(1))
      IF (NCHKD.LT.0)        GO TO 90
      CALL UBLOW  (KDHOLD(1),KARDCC(1),NCHKD)
      WRITE (IQPRNT,9012) INILEV,(KARDCC(J),J=1,NCHKD)
      WRITE (IQPRNT,9011)

      JCCTYP = JARTYP (KDHOLD(1))
      IF (JCCTYP.NE.0)       GO TO 14
   13 WRITE (IQPRNT,9013)
      GO TO 12

   14 CALL CCKRAK (KDHOLD(1))

      IF (JCCTYP.EQ.MCCQUI)  GO TO 92
      IF (JCCTYP.EQ.MCCPAM)  GO TO 31
      IF (JCCTYP.NE.MCCOPT)  GO TO 13

C----              HANDLE  +OPTION

   19 CALL SETOPT
      IF (INILEV.EQ.0)       GO TO 25
      JFL = 0
      N   = NOPINH(INILEV)

      DO 23  J=1,N
      JB   = JOPINH(J)
      JOLD = JBIT (MOPTSV,    JB)
      JNEW = JBIT (MOPTIO(31),JB)
      IF (JNEW.EQ.JOLD)      GO TO 23
      JFL = 7
      CALL SBIT (JOLD,MOPTIO(31),JB)
   23 CONTINUE
      IF (JFL.EQ.0)          GO TO 25

      WRITE (IQPRNT,9023) INILEV
 9023 FORMAT (1X/4H ***,16X,'INIT-LEVEL',I2,' IS TOO LATE',
     F' FOR CHANGING THIS OPTION   *****')
      JCCPT = 0
      GO TO 19

   25 IF (MOPTIO(3).EQ.0)    GO TO 12
      CALL SBIT0 (MOPTIO(31),3)
      CALL TOSETU
      GO TO 12

C--        +PAM, F=FNAME, T=ATTACH,RESUME,HOLD,DETACH, N=NSKIP,NDO

   31 JPAMCA = JPAMCA + 1
      CALL TOSETU
      IF (JCCF.EQ.0)         GO TO 35
      NVOLD(3) = MCCPAR(JCCF+1)

   35 NVOLD(5) = IOTYPE (MCCPAR(JCCPT+1),4)
      IOTON  = 256 + 2048
      NSKIP  = 0
      MAXEOF = 9999
      IF (NCCPN-1)           43,38,37
   37 NSKIP  = MCCPAR(JCCPN+1)
      JCCPN  = JCCPN + 3
   38 MAXEOF = MCCPAR(JCCPN+1) + NSKIP

C-------           START NEW BIG-FILE

   42 IOTON   = 256
   43 NVOLD(7)= -7
      INILEV = 3
      MCCTOU = 0

C-----     START NEW PAM,  READ PAM HEADER + TITLE RECORD, PRINT TITLE

   47 IF (NVOLD(7)+1.GE.MAXEOF)  GO TO 91
      CALL AUXFIL (0,NVOLD(1),4HPAM )
      IQ(LBUF+1) = 7
      CALL POPIN
      IF (NVARRI(1).EQ.4)    GO TO 91

      CALL POPIN
      LTK = LINBIN + NVARRI(9)
      CALL UBLOW (IQ(LTK),MWKX(1),80)
      WRITE (IQPRNT,9048) MWKX

C--                SKIP UNWANTED PAMS

      IF (NSKIP.EQ.0)        GO TO 60
      WRITE (IQPRNT,9054)
      IQ(LBUF+1) = -7
      NSKIP      = NSKIP - 1
   54 IF (NVARRI(3).EQ.3)    GO TO 47
      CALL POPIN
      GO TO 54


C-------           START NEW SECTION

   60 NCARDS = 0
      NSECTS = NSECTS + 1
      WRITE (IQPRNT,9060) NSECTS
      JMODDK = 2
      GO TO 68

C-----             READ RECORD BY RECORD

   62 CALL SETID (IDOLDV(1))
      IF (NVARRI(3).NE.2)    GO TO 64
      IF (LOGLEV.LT.1)       GO TO 63
      CALL UBLOW (NVARRI(5),NAME(1),8)
      WRITE (IQPRNT,9064) NAME

   63 JMODPA = 0
   64 CALL POPIN
      LTK = LINBIN + NVARRI(9)
      CALL KDCOPY (IQ(LTK))
      NCHKD  = KDNCHW*NWTK
      JCCTYP = MCCDEF - NVARRI(1)
      CALL CCKRAK (KIMA(1))
      MT     = MCCPAR(JCCPT+1)
      JMODDK = JMODPA
      IF (JBIT(MT,3) .NE.0)  JMODDK=0
      IF (JBIT(MT,1) .NE.0)  JMODDK=1
      IF (JBIT(MT,4) .NE.0)  JMODDK=2
      IF (JBIT(MT,24).NE.0)  JMODDK=3
      IF (JBIT(MT,25).NE.0)  JMODDK=4
      IF (NVARRI(1).EQ.2)  JMODPA=JMODDK
      GO TO 68
   67 CALL POPIN
   68 LTK = LINBIN + NVARRI(9)
      NCT = NVARRI(8)
      IF (NCT.EQ.0)          GO TO 77
      NCARDS = NCARDS + NCT

C----      UNPACK CARD BY CARD

      DO 72 I=1,NCT
      CALL KDCOPY (IQ(LTK))
C     NCHKD = MIN  (80, KDNCHW * NWTK)                                   UNI
      NCHKD = KDNCHW * NWTK                                             -UNI
      CALL TOCETA (KIMA(1))
   72 CONTINUE
      IF (LTK-LINBIN.NE.IQ(LINBIN)+1)   GO TO 81

   77 IF (NVARRI(3).EQ.0)    GO TO 67
      IF (NVARRI(3).NE.3)    GO TO 62
      NCHKD = 0
      CALL TOCETA (IQUEST)
      WRITE (IQPRNT,9079) NCARDS,NVNEW(9)
      NCHKD = -2
      CALL TOCETA (IQUEST)
      GO TO 47

C--                YTOBIN PACKING INCONSISTENCY

   81 WRITE (IQPRNT,9081) NDECKR
      GO TO 77

C----              EOI

   90 IF (INILEV.GE.3)       GO TO 92
      NCCPN = -7
      CALL TOSETU
      IQREAD = 0
      GO TO 42
   91 CALL AUXFIL (512,NVOLD(1),0)
      IF (IQREAD.NE.0)       GO TO 11
   92 NCHKD = -3
      CALL TOCETA (IQUEST)
      IOSPEC = MOPTIO(1)
      CALL AUXFIL (512,NVNEW(1),0)
      RETURN

 9011 FORMAT (1X)
 9012 FORMAT (10X,'LEV=',I1,3H - ,80A1)
 9013 FORMAT (4H ***,40X,'*** ILLEGAL C/C. IGNORED ***'/1X)
 9048 FORMAT (1X/1X,28(1H-),2X,4(10H---------+)/1X/1X,30X,80A1)
 9054 FORMAT (' SKIP INPUT.'/1X)
 9060 FORMAT (' WRITE SECTION',I4/1X)
 9064 FORMAT (3X,4HP = ,8A1)
 9079 FORMAT  (31X,'YTOCETA PACKED',I6,' CARDS -',I7,
     F' CETA RECORDS DONE.'/1X)
 9081 FORMAT (1X,3(/1X,44(1H*)),'   YTOBIN PACKING INCONSISTENCY DETECTE
     FD IN DECK',I6/1X)
      END
