*
* $Id$
*
* $Log$
* Revision 1.1  1996/02/26 17:16:35  mclareni
* Initial revision
*
*
#ifndef CERNLIB_COMIS_CSICHV_INC
#define CERNLIB_COMIS_CSICHV_INC
*
*
* csichv.inc
*
      COMMON/CSICHV/ICHLA,ICHLZ,ICHD0,ICHD9,ICHSUSC,
*--     ichar         'A'   'Z'  '0'   '9'   '_'
     + ICHSX,ICHSE,ICHBLN,KBLN,ICHQUO,ICHSSC,ICHSEQ,ICHBRA,ICHKET,
*--     '#'   '!'    ' '  bbbb  ''''   ';'    '='    '('    ')'
     + ICHMINU,ICHPLUS,ICHCOMM
*--      '-'     '+'     ','


#endif
