/*
 * $Id$
 *
 * $Log$
 * Revision 1.1  1996/03/01 11:38:56  mclareni
 * Initial revision
 *
 */
#include "paw/pilot.h"
/*CMZ :  2.07/09 18/08/95  15.06.20  by  O.Couet*/
/*-- Author :*/
/*
 * This file has been generated by the KUIP compiler.  Do NOT change it!
 *
 * KUIP header: 950303      Generation date: Fri Aug 18 15:06:18 1995
 *
 * Input file: pamcdf.txt
 */

#if (!defined(F77_LCASE)) && (!defined(F77_UCASE)) && (!defined(F77_USCORE))
#  if defined(__EXTENDED__) && (!defined(IBM370)) && (!defined(_IBMR2))
#    define IBM370
#  endif
#  if defined(CRAY) || defined(IBM370) || defined(vms)
#    define F77_UCASE
#  else
#    if ( defined(apollo) || defined(__apollo) ) && defined(APOFTN)
#      define F77_LCASE
#    else
#      define F77_USCORE
#    endif
#  endif
#endif

typedef int     IntFunc();
typedef char*   CharFunc();
typedef char** pCharFunc();
typedef void    SUBROUTINE();
#ifdef IBM370
#  pragma linkage(SUBROUTINE,FORTRAN)
#endif

extern void klnkmenu();
extern void klnkbrcl();
extern void klnkkmcl();
extern void klnkicon();
extern void klnkbutt();

typedef unsigned long KmPixmap; /* Pixmap from <X11/X.h>                   */
 typedef void *KmWidget;         /* Widget from <X11/Intrinsic.h>           */
 typedef void *KmCalldata;       /* XmAnyCallbackStruct from <Motif/Xm.h>   */
                                 /*                                         */
 typedef enum {                  /*                                         */
   BRACT_OPEN = 0,               /*                                         */
   BRACT_ROOT = 1,               /*                                         */
   BRACT_CONT = 2,               /*                                         */
   BRACT_GRAF = 3                /*                                         */
 } BrActTag;                     /*                                         */
                                 /*                                         */
 typedef enum {                  /*                                         */
   BrActUpdate    = 0x01,        /* browser window has to be updated ('!')  */
   BrActSeparator = 0x02,        /* put separator in menu ('/')             */
   BrActToggle    = 0x04,        /* register as toggle button               */
   BrActToggleOn  = 0x08,        /* toggle state is on                      */
   BrActSensitive = 0x10         /* button is sensitive                     */
 } BrActFlag;                    /*                                         */
                                 /*                                         */

typedef struct _BrAction {      /*                                         */
  struct _BrAction *next;       /* link to next action binding             */
  BrActFlag   flags;            /*                                         */
  char       *text;             /* text line in menu                       */
  char       *user_text;        /* user text overriding CDF text (malloced)*/
  char       *accel;            /* accelerator                             */
  char       *exec;             /* action commands                         */
  SUBROUTINE *call_F;           /* action routine                          */
  IntFunc    *call_C;           /* action function                         */
  BrActTag    tag;              /* for which window the action is defined  */
  struct _BrClass *class;       /* pointer to BrClass in case of open menu */
 } BrAction;                     /*                                         */
                                 /*                                         */
 typedef struct _BrClass {       /*                                         */
   struct _BrClass *next;        /* link to next browsable class            */
   char       *name;             /* unique identifier name                  */
   char       *title;            /* title for popup menu (maybe NULL)       */
   SUBROUTINE *scan_km_F;        /* user function scanning the directory    */
   pCharFunc  *scan_km_C;        /* user function scanning the directory    */
   SUBROUTINE *scan_br_F;        /* user function scanning for browsables   */
   pCharFunc  *scan_br_C;        /* user function scanning for browsables   */
   BrAction   *root;             /* list of actions in root window          */
   BrAction   *open;             /* list of actions in open menu            */
 } BrClass;                      /*                                         */
                                 /*                                         */

typedef struct _KmIcon {        /*                                         */
  struct _KmIcon *next;         /* link to next icon                       */
  char       *name;             /* unique identifier name                  */
  int         width;            /* width of the pixmap                     */
  int         height;           /* height of the pixmap                    */
  char       *bitmap;           /* bitmap data                             */
  KmPixmap    pix;              /* filled in Motif part                    */
  KmPixmap    hi_pix;           /* high lighted pixmap                     */
 } KmIcon;                       /*                                         */
                                 /*                                         */
 typedef struct _KmClass {       /*                                         */
   struct _KmClass *next;        /* link to next object class               */
   int         is_dir;           /* flag if class has is a directory        */
   char       *name;             /* unique identifier name                  */
   char       *title;            /* title for popup menu (maybe NULL)       */
   char       *big_icon;         /* name of the big icon                    */
   KmIcon     *bicon;            /* pointer to the big icon structure       */
   char       *sm_icon;          /* name of the small icon                  */
   KmIcon     *sicon;            /* pointer to the small icon structure     */
   SUBROUTINE *user_icon_F;      /* user function to return icon bitmap     */
   IntFunc    *user_icon_C;      /* user function to return icon bitmap     */
   BrAction   *cont;             /* list of actions in content window       */
   BrAction   *graf;             /* list of actions in graphics window      */
   int         obj_count;        /* number of objects in content window     */
 } KmClass;                      /*                                         */
                                 /*                                         */

typedef enum {                  /*                                         */
  KmButtSensitive       = 0x00, /* sensitive button                        */
  KmButtNonSensitive    = 0x01, /* non-sensitive button ('NS')             */
  KmButtToggleSensitive = 0x02, /* toggle-sensitive button ('TS')          */
  KmButtSensitivityMask = 0x03, /* mask for sensitivity type               */
  KmButtSeparator       = 0x04, /* put separator in menu ('/')             */
  KmButtBrowser         = 0x08  /* button is in main browser ('BR')        */
 } KmButtFlag;                   /*                                         */
                                 /*                                         */
 typedef struct _KmButton {      /*                                         */
   struct _KmButton *next;       /* button label or menu item               */
   char       *menu;             /* menu name or NULL for buttons           */
   char       *label;            /* button label or menu item               */
   SUBROUTINE *call_F;           /* callback routine (FORTRAN)              */
   IntFunc    *call_C;           /* callback routine (C)                    */
   char       *action;           /* name of callback routine                */
   char       *mnemo;            /* button mnemonic                         */
   char       *accel;            /* button accelerator                      */
   char       *accel_text;       /* button accelerator text                 */
   KmButtFlag  flags;            /* sensitivity type etc.                   */
   KmWidget    widget;           /* Motif widget ID                         */
 } KmButton;                     /*                                         */
                                 /*                                         */

extern struct {                        /*
    */   /* indirect calls to avoid linking HIGZ
    */   IntFunc    *graf_info_C;      /* pass display, open and close
 (ixmotif)  */   SUBROUTINE *graf_size_F;      /* resize window (IGRSIZ)
            */   SUBROUTINE *graf_pick_F;      /* identifying graphics objects
 (IGOBJ)    */   SUBROUTINE *graf_attr_F;      /* set attributes (IGSET)
            */   SUBROUTINE *graf_close_F;     /* close workstation (ICLWK)
            */   /* optional routines for Motif customization
            */   pCharFunc  *user_FallBk_C;    /* get application fallbacks
            */   IntFunc    *user_TopWid_C;    /* pass toplevel widget
 identifiers        */ } klnkaddr;                     /*
                    */

typedef enum {                  /*                                         */
  KmFLAG_FORGET = 0x01,         /* last value is not kept for Motif panels */
  KmFLAG_MINUS  = 0x02,         /* -VALUE is not an abbrev for CHOPT=VALUE */
  KmFLAG_QUOTE  = 0x04,         /* do not remove quotes                    */
  KmFLAG_VARARG = 0x08,         /* append additional args to this param.   */
  KmFLAG_CONST  = 0x10,         /* do not allow to assign a value          */
  KmFLAG_HIDDEN = 0x20,         /* do not show in menus                    */
  KmFLAG_SEPARATE = 0x40        /* treat arguments as separate tokens      */
 } KmParFlag;                    /*                                         */
                                 /*                                         */
 typedef enum {                  /*                                         */
   KmTYPE_CHAR   = 'C',          /* character string                        */
   KmTYPE_FILE   = 'F',          /* file name                               */
   KmTYPE_INT    = 'I',          /* integer                                 */
   KmTYPE_OPTION = 'O',          /* option                                  */
   KmTYPE_REAL   = 'R'           /* real                                    */
 } KmParType;                    /*                                         */
                                 /*                                         */

typedef struct {                /* file name                               */
  char         *filter_default; /* filter wildcard                         */
  char         *filter_current; /* current filter                          */
 } KmParFile;                    /*                                         */
                                 /*                                         */
 typedef struct {                /*                                         */
   char         *range_lower;    /* lower value of range                    */
   char         *range_upper;    /* upper value of range                    */
   char         *slider_lower;   /* lower limit for slider                  */
   char         *slider_upper;   /* upper limit for slider                  */
   int           decimals;       /* number of decimals used for slider      */
 } KmParInt;                     /*                                         */
                                 /*                                         */
 typedef struct {                /* option                                  */
   char        **text;           /* explanations (parallel to range_value)  */
   int          *mutex;          /* mutex group to which text belongs       */
   int          *radio;          /* radio group to which text belongs       */
 } KmParOption;                  /*                                         */
                                 /*                                         */

typedef KmParInt KmParReal;     /* real and int have the same fields       */
                                /*                                         */
 typedef struct {                /*                                         */
   char         *name;           /* parameter name                          */
   int           abbrev;         /* minimum length that name is recognized  */
   char         *prompt;         /* prompt string                           */
   char         *dfault;         /* default value                           */
   char         *last;           /* last value for Motif panel (malloced)   */
   int           width;          /* width of input field                    */
   int           range_count;    /* number of items in range_value          */
   char        **range_value;    /* list of allowed values                  */
   int           select_count;   /* number of items in select_count         */
   char        **select_value;   /* list of values for selection box        */
   KmParFlag     flags;          /* special flags                           */
   KmParType     type;           /* parameter type                          */
   void        *ptype;           /* structure pointer selected by type      */
 } KmParameter;                  /*                                         */
                                 /*                                         */

typedef struct _KmCommand {     /*                                         */
  struct _KmCommand *next;      /* link to next command                    */
  char         *path;           /* command path                            */
  char         *name;           /* command name                            */
  int           hidden;         /* flag if command is invisible            */
  int           level;          /* depth of submenus                       */
  int           total;          /* total number of parameters              */
  int           mandatory;      /* number of mandatory parameters          */
  KmParameter **par;            /* list of total parameter descriptions    */
  int           list_par;       /* index+1 of parameter taking a list      */
  int           xcount;         /* count number of action calls            */
  SUBROUTINE   *action_F;       /* action routine                          */
  IntFunc      *action_C;       /* action routine                          */
  SUBROUTINE   *user_help_F;    /* user help routine                       */
  pCharFunc    *user_help_C;    /* user help routine                       */
  int          nguidance;       /* number of lines in guidance text        */
  char        **guidance;       /* help text                               */
  int          nkeyword;        /* number of lines for keywords            */
  char        **keyword;        /* list of keywords                        */
  int          nhlink;          /* number of lines for links               */
  char        **hlink;          /* list of links                           */
  int           argc;           /* number of arguments entered             */
  char        **argv;           /* argc argument values                    */
  char         *argline;        /* argument line as entered                */
  int          *argoffs;        /* argc offsets into argline for KUGETE    */
 } KmCommand;                    /*                                         */
                                 /*                                         */

typedef struct _KmMenu {        /*                                         */
  struct _KmMenu *next;         /* link to next menu                       */
  struct _KmMenu *down;         /* link to submenu                         */
  char         *path;           /* path of parent menu                     */
  char         *name;           /* menu name                               */
  int           level;          /* depth of submenus                       */
  KmCommand    *cmds;           /* link to first command                   */
  int          nguidance;       /* number of lines in guidance text        */
  char        **guidance;       /* help text                               */
  int          nkeyword;        /* number of lines for keywords            */
  char        **keyword;        /* list of keywords                        */
  int          nhlink;          /* number of lines for links               */
  char        **hlink;          /* list of links                           */
 } KmMenu;                       /*                                         */
                                 /*                                         */
 extern void klnkbrcl();         /*                                         */
 extern void klnkicon();         /*                                         */
 extern void klnkkmcl();         /*                                         */
 extern void klnkmenu();         /*                                         */
                                 /*                                         */

#ifdef F77_LCASE
#  define pamdef_ pamdef
#  define pbhist_ pbhist
#  define pbhlun_ pbhlun
#  define pbpiaf_ pbpiaf
#  define pbplun_ pbplun
#  define igrsiz_ igrsiz
#  define igobj_ igobj
#  define igset_ igset
#  define iclwk_ iclwk
#endif

#ifdef F77_UCASE
#  define pamdef_ PAMDEF
#  define pbhist_ PBHIST
#  define pbhlun_ PBHLUN
#  define pbpiaf_ PBPIAF
#  define pbplun_ PBPLUN
#  define igrsiz_ IGRSIZ
#  define igobj_ IGOBJ
#  define igset_ IGSET
#  define iclwk_ ICLWK
#endif

#ifdef IBM370
#  pragma linkage(PAMDEF,FORTRAN)
#  pragma linkage(PBHIST,FORTRAN)
#  pragma linkage(PBHLUN,FORTRAN)
#  pragma linkage(PBPIAF,FORTRAN)
#  pragma linkage(PBPLUN,FORTRAN)
#  pragma linkage(IGRSIZ,FORTRAN)
#  pragma linkage(IGOBJ,FORTRAN)
#  pragma linkage(IGSET,FORTRAN)
#  pragma linkage(ICLWK,FORTRAN)
#endif

extern void pamdef_();
extern void pbhist_();
extern void pbhlun_();
extern void pbpiaf_();
extern void pbplun_();
extern void igrsiz_();
extern void igobj_();
extern void igset_();
extern void iclwk_();

extern int show_closeFbDialog();
extern int show_openFbDialog();
extern char **blist_chains();
extern char **blist_hbook_files();
extern char **bset_hbook_dir();
extern int show_histoStyle();
extern int default_action();
extern int default_G_action();
extern int fitting_action();
extern int bdelete_entry();
extern int kxterm_show_style();
extern int ixmotif();
extern char **get_paw_fallbacks();
extern int init_top_level_window();

void pamdef_()
{

static char *_MOTIF_HELP_EXE_RESOURCES_guidance[] = {
 "       *** X Resources for Paw++ ***", "", "",
 "This is a list of the X resources available to Paw++.",
 "Resources control the appearance and behavior of an application.", "",
 "Users can specify their own values for",
 "these resources in the standard X/Motif way",
 "(via their own .Xdefaults file or the system wide",
 "/usr/lib/X11/app-defaults/Paw++ file).", "",
 "Any default values specified by Paw++ are given",
 "behind the resource name.", "", "", "",
 " Paw++*kxtermGeometry:                 650x450+0+0", "",
 "Geometry of Kxterm, the kuip terminal emulator (Paw++ Executive Window).",
 "", " Paw++*kuipGraphics_shell.geometry:    600x600-0+0", "",
 "Geometry of the Graphics Window(s) (if any).", "",
 " Paw++*kuipBrowser_shell.geometry:     +0+485", "",
 "Geometry of the Browser(s).", "",
 " Paw++*histoStyle_shell.geometry:      +670+635", "",
 "Geometry of the Style Panel.", "", " Paw++*ntupleBrowser_shell.geometry:",
 "", "Geometry of the Ntuple Viewer.", "",
 " Paw++*XmText*fontList:           *-courier-medium-r-normal--12-120-*",
 "                                  *-prestige-medium-r-normal-*-120-* (on\
 HP)",
 " Paw++*XmTextField*fontList:      *-courier-medium-r-normal--12-120-*",
 "                                  *-prestige-medium-r-normal-*-120-* (on\
 HP)", "", "Font used by all text areas.", "",
 " Paw++*kxtermFont:                *-helvetica-bold-r-normal--12-120-*",
 "                                  *-swiss*742-bold-r-normal-*-120-* (on\
 HP)", "", "Font used by Kxterm (Paw++ Executive Window).", "",
 " Paw++*kxtermTextFont:            *-courier-medium-r-normal--12-120-*",
 "                                  *-prestige-medium-r-normal-*-120-* (on\
 HP)", "", "Font used in the Kxterm text areas.", "",
 " Paw++*dirlist*fontList:          *-courier-bold-r-normal--12-120-*",
 "                                  *-courier-bold-r-normal-*-120-* (on HP)",
 "", "Font used for the icon labels in the browser.", "",
 " Paw++*matrix.fontList:           *-courier-medium-r-normal--12-120-*",
 "                                  *-prestige-medium-r-normal-*-120-* (on\
 HP)", "", "Font used for the Ntuple/Scan matrix (accessable via the Ntuple",
 "Viewer).", "",
 " Paw++*helpFont:                  *-courier-medium-r-normal--12-120-*",
 "                                  *-prestige-medium-r-normal-*-120-* (on\
 HP)", "", "Font used for help windows.", "",
 " Paw++*fontList:                  *-helvetica-bold-r-normal--12-120-*",
 "                                  *-swiss*742-bold-r-normal-*-120-* (on\
 HP)", "", "Font for the menus, messages and boxes.", "",
 " Paw++*keyboardFocusPolicy:       pointer", "",
 "If \"explicit\", focus is determined by a mouse or keyboard command.",
 "If \"pointer\" (default), focus is determined by the mouse pointer",
 "position.", "", " Paw++*doubleClickInterval:       400", "",
 "The time span (in milliseconds) within which two button clicks",
 "must occur to be considered a double click rather than two single",
 "clicks.", "", " Paw++*userMailText.value:",
 " Paw++*instituteMailText.value:", " Paw++*phoneMailText.value:",
 " Paw++*emailMailText.value:", "",
 "Using these resource one can preset the values for the user, institute,",
 "phone and email text fields in the \"Mail Paw++ Developers\" dialog.", "",
 " Paw++*background:", "", "Specify the background color for all windows.",
 "", " Paw++*foreground:", "",
 "Specify the foreground color for all windows.", "",
 " Paw++*dirlist*background:", "",
 "Specify the background color for the iconbox part of the browser.", "",
 " Paw++*dirlist*<object>*iconForeground:          grey40", "",
 "Specify the foreground color for the icons of type <object>.", "",
 " Paw++*dirlist*<object>*iconBackground:          white", "",
 "Specify the background color for the icons of type <object>.", "",
 " Paw++*dirlist*<object>*iconLabelForeground:     white", "",
 "Specify the foreground color for the labels of the icons of type <object>.",
 "", " Paw++*dirlist*<object>*iconLabelBackground:     black", "",
 "Specify the background color for the labels of the icons of type <object>.",
 "", "Currently the following different <object>'s are defined:", "",
 " dir     -- directory", " 1d      -- 1d histograms",
 " 2d      -- 2d histograms", " ntuple  -- Ntuples",
 " pict    -- Higz pictures", " chain   -- Ntuple chains",
 " entry   -- Ntuple chain entries", " hbook   -- Hbook files", "",
 "The default iconForeground and iconBackground colors for these objects\
 are:", "", " Paw++*dirlist*dir*iconForeground:      blue",
 " Paw++*dirlist*1d*iconForeground:       DarkGoldenrod3",
 " Paw++*dirlist*2d*iconForeground:       DeepPink3",
 " Paw++*dirlist*ntuple*iconForeground:   SteelBlue3",
 " Paw++*dirlist*pict*iconForeground:     green4",
 " Paw++*dirlist*chain*iconForeground:    blue",
 " Paw++*dirlist*entry*iconForeground:    OrangeRed", "",
 "When using a black and white X Server use the following resource",
 "settings to make the icons visible:", "",
 " Paw++*dirlist*<object>*iconForeground:          black",
 " Paw++*dirlist*<object>*iconBackground:          white",
 " Paw++*dirlist*<object>*iconLabelForeground:     black",
 " Paw++*dirlist*<object>*iconLabelBackground:     white" };
static KmCommand _MOTIF_HELP_EXE_RESOURCES = {  (KmCommand*)0,
 "/MOTIF/HELP_EXE_RESOURCES", "HELP_EXE_RESOURCES", 0, 1, 0, 0,
 (KmParameter**)0, 0, 0, (SUBROUTINE*)0, (IntFunc*)0, (SUBROUTINE*)0,
 (pCharFunc*)0, 150, _MOTIF_HELP_EXE_RESOURCES_guidance, 0, (char**)0, 0,
 (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static char *_MOTIF_HELP_EXE_guidance[] = { "       *** Paw++ ***", "", "",
 "Paw++ is a new and powerful OSF/Motif based Graphical User Interface",
 "to the popular Physics Analysis Workstation (PAW).",
 "The graphical user interface makes the full and rich command set",
 "of PAW available to even the naive user. Simple point and click",
 "operations are enough to execute commands that were previously",
 "accessable only to expert users.", "",
 "Paw++ starts up with three windows on the screen:", "",
 "- The \"Paw++ Executive Window\" (Kxterm) contains (from top to bottom)",
 "  --- a menu bar", "  --- a transcript pad + hold button (H)",
 "  --- a current working directory indicator",
 "  --- an input pad + hold button (H)", "",
 "For more information on Kxterm see the Kxterm \"Help\" menu.", "",
 "- The \"Paw++ Graphics 1\" window displays the graphics output from\
 HIGZ/X11.",
 "Objects, e.g. histograms, displayed in the graphics window can be",
 "manipulated by pointing at them, pressing the right mouse button and",
 "selecting an operation from the popup menu. Pointing at the edge of the",
 "graphics window (between displayed object and window border) brings",
 "up a general popup menu. Up to 4 additional graphics windows can be opened",
 "by selecting \"Open New Window\" from this menu.", "",
 "- The \"Paw++ Main Browser\" displays all browsable classes and connected",
 "hbook files. Up to 4 additional browsers can be opened via the \"View\"",
 "menu of the \"Paw++ Executive Window\" or via the \"Clone\" button on the",
 "browsers. For more information on the browsers see the \"Help\" menus.", "",
 "", "Via the \"View\" menu of the \"Paw++ Executive Window\" one can open:",
 "",
 "- A \"Command Panel\" containing buttons for frequently used command\
 sequences.",
 "See HELP_PANEL, HELP_EDIT_PANEL and HELP_SAVE_PANEL for information on how",
 "to define command panels.", "", "- Additional browsers.", "",
 "- A \"Style Panel\" for changing all possible histogram plotting options." };
static KmCommand _MOTIF_HELP_EXE = { &_MOTIF_HELP_EXE_RESOURCES,
 "/MOTIF/HELP_EXE", "HELP_EXE", 0, 1, 0, 0, (KmParameter**)0, 0, 0,
 (SUBROUTINE*)0, (IntFunc*)0, (SUBROUTINE*)0, (pCharFunc*)0, 43,
 _MOTIF_HELP_EXE_guidance, 0, (char**)0, 0, (char**)0, 0, (char**)0, (char*)0,
 (int*)0 };

static char *_MOTIF_HELP_Chains_guidance[] = {
 "       *** Class \"Chains\" ***", "", "",
 "The class \"Chains\" allows to browse all defined chains. See the",
 "command Ntuple/Chain for more information." };
static KmCommand _MOTIF_HELP_Chains = { &_MOTIF_HELP_EXE,
 "/MOTIF/HELP_Chains", "HELP_Chains", 0, 1, 0, 0, (KmParameter**)0, 0, 0,
 (SUBROUTINE*)0, (IntFunc*)0, (SUBROUTINE*)0, (pCharFunc*)0, 5,
 _MOTIF_HELP_Chains_guidance, 0, (char**)0, 0, (char**)0, 0, (char**)0,
 (char*)0, (int*)0 };

static char *_MOTIF_HELP_Hbook_guidance[] = {
 "       *** Class \"Hbook\" ***", "", "",
 "The class \"Hbook\" allows to browse the file system for Hbook",
 "files. Hbook files are files with the extension \".hbook\"." };
static KmCommand _MOTIF_HELP_Hbook = { &_MOTIF_HELP_Chains,
 "/MOTIF/HELP_Hbook", "HELP_Hbook", 0, 1, 0, 0, (KmParameter**)0, 0, 0,
 (SUBROUTINE*)0, (IntFunc*)0, (SUBROUTINE*)0, (pCharFunc*)0, 5,
 _MOTIF_HELP_Hbook_guidance, 0, (char**)0, 0, (char**)0, 0, (char**)0,
 (char*)0, (int*)0 };

static KmMenu _MOTIF = {  (KmMenu*)0,  (KmMenu*)0, "/MOTIF", "MOTIF", 1,
 &_MOTIF_HELP_Hbook, 0, (char**)0, 0, (char**)0, 0, (char**)0 };

static BrAction brclass_6_root_4 = { (BrAction*)0, (BrActFlag)17, "Close",
 (char*)0, (char*)0, "Close [unit]", (SUBROUTINE*)0, (IntFunc*)0, BRACT_ROOT,
 (BrClass*)0 };
static BrAction brclass_6_root_3 = { &brclass_6_root_4, (BrActFlag)18,
 "Clear", (char*)0, (char*)0, "Picture/Scratch *", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_ROOT, (BrClass*)0 };
static BrAction brclass_6_root_2 = { &brclass_6_root_3, (BrActFlag)18,
 "Copy to //PAWC", (char*)0, (char*)0, "Izin *", (SUBROUTINE*)0, (IntFunc*)0,
 BRACT_ROOT, (BrClass*)0 };
static BrAction brclass_6_root_1 = { &brclass_6_root_2, (BrActFlag)16, "List",
 (char*)0, (char*)0, "Cdir [path]", (SUBROUTINE*)0, (IntFunc*)0, BRACT_ROOT,
 (BrClass*)0 };
static BrClass brclass_6 = { (BrClass*)0, "HIGZ", "Pictures in RZ File",
 pbhist_, (pCharFunc*)0, pbhlun_, (pCharFunc*)0, &brclass_6_root_1,
 (BrAction*)0 };

static BrAction brclass_5_root_7 = { (BrAction*)0, (BrActFlag)17, "Close",
 (char*)0, (char*)0, "Close [unit]", (SUBROUTINE*)0, (IntFunc*)0, BRACT_ROOT,
 (BrClass*)0 };
static BrAction brclass_5_root_6 = { &brclass_5_root_7, (BrActFlag)18,
 "Clear", (char*)0, (char*)0, "Histo/Hio/Hscratch 0", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_ROOT, (BrClass*)0 };
static BrAction brclass_5_root_5 = { &brclass_5_root_6, (BrActFlag)18,
 "Create N-tuple", (char*)0, (char*)0, "Ntuple/Create CHRZPA=[path]",
 (SUBROUTINE*)0, (IntFunc*)0, BRACT_ROOT, (BrClass*)0 };
static BrAction brclass_5_root_4 = { &brclass_5_root_5, (BrActFlag)16,
 "Write from //PAWC...", (char*)0, (char*)0, "-Hio/Hrout 0 T", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_ROOT, (BrClass*)0 };
static BrAction brclass_5_root_3 = { &brclass_5_root_4, (BrActFlag)16,
 "Add to //PAWC", (char*)0, (char*)0, "Hio/Hrin 0 ! 99999", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_ROOT, (BrClass*)0 };
static BrAction brclass_5_root_2 = { &brclass_5_root_3, (BrActFlag)18,
 "Copy to //PAWC", (char*)0, (char*)0, "Hio/Hrin 0", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_ROOT, (BrClass*)0 };
static BrAction brclass_5_root_1 = { &brclass_5_root_2, (BrActFlag)16, "List",
 (char*)0, (char*)0, "Cdir [path]", (SUBROUTINE*)0, (IntFunc*)0, BRACT_ROOT,
 (BrClass*)0 };
static BrAction brclass_5_open_2 = { (BrAction*)0, (BrActFlag)17,
 "Close Hbook File...", (char*)0, (char*)0, (char*)0, (SUBROUTINE*)0,
 show_closeFbDialog, BRACT_OPEN, (BrClass*)0 };
static BrAction brclass_5_open_1 = { &brclass_5_open_2, (BrActFlag)17,
 "Open Hbook File...", (char*)0, (char*)0, (char*)0, (SUBROUTINE*)0,
 show_openFbDialog, BRACT_OPEN, (BrClass*)0 };
static BrClass brclass_5 = { &brclass_6, "HBOOK", "Histograms in RZ File",
 pbhist_, (pCharFunc*)0, pbhlun_, (pCharFunc*)0, &brclass_5_root_1,
 &brclass_5_open_1 };

static BrAction brclass_4_root_7 = { (BrAction*)0, (BrActFlag)18, "Clear",
 (char*)0, (char*)0, "-Histo/Delete 0", (SUBROUTINE*)0, (IntFunc*)0,
 BRACT_ROOT, (BrClass*)0 };
static BrAction brclass_4_root_6 = { &brclass_4_root_7, (BrActFlag)16,
 "Create N-tuple", (char*)0, (char*)0, "Ntuple/Create", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_ROOT, (BrClass*)0 };
static BrAction brclass_4_root_5 = { &brclass_4_root_6, (BrActFlag)16,
 "Create 2d     ", (char*)0, (char*)0, "Histo/Create/2d", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_ROOT, (BrClass*)0 };
static BrAction brclass_4_root_4 = { &brclass_4_root_5, (BrActFlag)16,
 "Create Var-Bin", (char*)0, (char*)0, "Histo/Create/Bins", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_ROOT, (BrClass*)0 };
static BrAction brclass_4_root_3 = { &brclass_4_root_4, (BrActFlag)16,
 "Create Profile", (char*)0, (char*)0, "Histo/Create/Profile", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_ROOT, (BrClass*)0 };
static BrAction brclass_4_root_2 = { &brclass_4_root_3, (BrActFlag)18,
 "Create 1d     ", (char*)0, (char*)0, "Histo/Create/1d", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_ROOT, (BrClass*)0 };
static BrAction brclass_4_root_1 = { &brclass_4_root_2, (BrActFlag)16, "List",
 (char*)0, (char*)0, "Cdir [path]", (SUBROUTINE*)0, (IntFunc*)0, BRACT_ROOT,
 (BrClass*)0 };
static BrClass brclass_4 = { &brclass_5, "PAWC",
 "Histograms and Pictures in Memory", pbhist_, (pCharFunc*)0, pbhlun_,
 (pCharFunc*)0, &brclass_4_root_1, (BrAction*)0 };

static BrAction brclass_3_root_2 = { (BrAction*)0, (BrActFlag)17,
 "Delete All Chains", (char*)0, (char*)0, "Chain -", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_ROOT, (BrClass*)0 };
static BrAction brclass_3_root_1 = { &brclass_3_root_2, (BrActFlag)17, "List",
 (char*)0, (char*)0, (char*)0, (SUBROUTINE*)0, (IntFunc*)0, BRACT_ROOT,
 (BrClass*)0 };
static BrClass brclass_3 = { &brclass_4, "Chains", (char*)0, (SUBROUTINE*)0,
 blist_chains, (SUBROUTINE*)0, (pCharFunc*)0, &brclass_3_root_1, (BrAction*)0
 };

static BrAction brclass_2_root_1 = { (BrAction*)0, (BrActFlag)16, "List",
 (char*)0, (char*)0, (char*)0, (SUBROUTINE*)0, (IntFunc*)0, BRACT_ROOT,
 (BrClass*)0 };
static BrClass brclass_2 = { &brclass_3, "Piaf", "Files on Piaf", pbpiaf_,
 (pCharFunc*)0, pbplun_, (pCharFunc*)0, &brclass_2_root_1, (BrAction*)0 };

static BrAction brclass_1_root_1 = { (BrAction*)0, (BrActFlag)16, "List",
 (char*)0, (char*)0, (char*)0, (SUBROUTINE*)0, (IntFunc*)0, BRACT_ROOT,
 (BrClass*)0 };
static BrClass brclass_1 = { &brclass_2, "Hbook", (char*)0, (SUBROUTINE*)0,
 blist_hbook_files, (SUBROUTINE*)0, bset_hbook_dir, &brclass_1_root_1,
 (BrAction*)0 };

static BrAction kmclass_15_graf_1 = { (BrAction*)0, (BrActFlag)16,
 "Statistics Off", (char*)0, (char*)0, "Option NSTA", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static KmClass kmclass_15 = { (KmClass*)0, 0, "stat-box", "Statistics Box",
 (char*)0, (KmIcon*)0, (char*)0, (KmIcon*)0, (SUBROUTINE*)0, (IntFunc*)0,
 (BrAction*)0, &kmclass_15_graf_1, 0 };

static BrAction kmclass_14_graf_11 = { (BrAction*)0, (BrActFlag)16,
 "Axis Color...", (char*)0, (char*)0, "-Set YCOL ; Hist/plot [this]",
 (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_14_graf_10 = { &kmclass_14_graf_11, (BrActFlag)16,
 "Character Font...", (char*)0, (char*)0, "-Set VFON ; Hist/plot [this]",
 (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_14_graf_9 = { &kmclass_14_graf_10, (BrActFlag)16,
 "Values Distance...", (char*)0, (char*)0, "-Set XVAL ; Hist/plot [this]",
 (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_14_graf_8 = { &kmclass_14_graf_9, (BrActFlag)16,
 "Tick marks length...", (char*)0, (char*)0, "-Set YTIC ; Hist/plot [this]",
 (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_14_graf_7 = { &kmclass_14_graf_8, (BrActFlag)18,
 "Number of divisions...", (char*)0, (char*)0, "-Set NDVY ; Hist/plot [this]",
 (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_14_graf_6 = { &kmclass_14_graf_7, (BrActFlag)16,
 "Sort by decreasing channel contents", (char*)0, (char*)0,
 "Sort [this] VY ; Hist/plot [this]", (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF,
 (BrClass*)0 };
static BrAction kmclass_14_graf_5 = { &kmclass_14_graf_6, (BrActFlag)16,
 "Sort by increasing channel contents", (char*)0, (char*)0,
 "Sort [this] DY ; Hist/plot [this]", (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF,
 (BrClass*)0 };
static BrAction kmclass_14_graf_4 = { &kmclass_14_graf_5, (BrActFlag)16,
 "Sort in reverse alphabetical order", (char*)0, (char*)0,
 "Sort [this] EY ; Hist/plot [this]", (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF,
 (BrClass*)0 };
static BrAction kmclass_14_graf_3 = { &kmclass_14_graf_4, (BrActFlag)18,
 "Sort in alphabetical order", (char*)0, (char*)0,
 "Sort [this] AY ; Hist/plot [this]", (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF,
 (BrClass*)0 };
static BrAction kmclass_14_graf_2 = { &kmclass_14_graf_3, (BrActFlag)16,
 "Linear", (char*)0, (char*)0, "Option LINY ; Hist/plot [this]",
 (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_14_graf_1 = { &kmclass_14_graf_2, (BrActFlag)16,
 "Logarithmic", (char*)0, (char*)0, "Option LOGY ; Hist/plot [this]",
 (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static KmClass kmclass_14 = { &kmclass_15, 0, "y-axis", "Y Axis", (char*)0,
 (KmIcon*)0, (char*)0, (KmIcon*)0, (SUBROUTINE*)0, (IntFunc*)0, (BrAction*)0,
 &kmclass_14_graf_1, 0 };

static BrAction kmclass_13_graf_11 = { (BrAction*)0, (BrActFlag)16,
 "Axis Color...", (char*)0, (char*)0, "-Set XCOL ; Hist/plot [this]",
 (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_13_graf_10 = { &kmclass_13_graf_11, (BrActFlag)16,
 "Character Font...", (char*)0, (char*)0, "-Set VFON ; Hist/plot [this]",
 (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_13_graf_9 = { &kmclass_13_graf_10, (BrActFlag)16,
 "Values Distance...", (char*)0, (char*)0, "-Set YVAL ; Hist/plot [this]",
 (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_13_graf_8 = { &kmclass_13_graf_9, (BrActFlag)16,
 "Tick marks length...", (char*)0, (char*)0, "-Set XTIC ; Hist/plot [this]",
 (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_13_graf_7 = { &kmclass_13_graf_8, (BrActFlag)18,
 "Number of divisions...", (char*)0, (char*)0, "-Set NDVX ; Hist/plot [this]",
 (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_13_graf_6 = { &kmclass_13_graf_7, (BrActFlag)16,
 "Sort by decreasing channel contents", (char*)0, (char*)0,
 "Sort [this] VX ; Hist/plot [this]", (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF,
 (BrClass*)0 };
static BrAction kmclass_13_graf_5 = { &kmclass_13_graf_6, (BrActFlag)16,
 "Sort by increasing channel contents", (char*)0, (char*)0,
 "Sort [this] DX ; Hist/plot [this]", (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF,
 (BrClass*)0 };
static BrAction kmclass_13_graf_4 = { &kmclass_13_graf_5, (BrActFlag)16,
 "Sort in reverse alphabetical order", (char*)0, (char*)0,
 "Sort [this] EX ; Hist/plot [this]", (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF,
 (BrClass*)0 };
static BrAction kmclass_13_graf_3 = { &kmclass_13_graf_4, (BrActFlag)18,
 "Sort in alphabetical order", (char*)0, (char*)0,
 "Sort [this] AX ; Hist/plot [this]", (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF,
 (BrClass*)0 };
static BrAction kmclass_13_graf_2 = { &kmclass_13_graf_3, (BrActFlag)16,
 "Linear", (char*)0, (char*)0, "Option LINX ; Hist/plot [this]",
 (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_13_graf_1 = { &kmclass_13_graf_2, (BrActFlag)16,
 "Logarithmic", (char*)0, (char*)0, "Option LOGX ; Hist/plot [this]",
 (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static KmClass kmclass_13 = { &kmclass_14, 0, "x-axis", "X Axis", (char*)0,
 (KmIcon*)0, (char*)0, (KmIcon*)0, (SUBROUTINE*)0, (IntFunc*)0, (BrAction*)0,
 &kmclass_13_graf_1, 0 };

static BrAction kmclass_12_graf_12 = { (BrAction*)0, (BrActFlag)16,
 "Deactivate Window", (char*)0, (char*)0, "Work [this] D", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_12_graf_11 = { &kmclass_12_graf_12, (BrActFlag)16,
 "Activate Window", (char*)0, (char*)0, "Work [this] A", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_12_graf_10 = { &kmclass_12_graf_11, (BrActFlag)16,
 "Close Window", (char*)0, (char*)0, "Work [this] C", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_12_graf_9 = { &kmclass_12_graf_10, (BrActFlag)18,
 "Open New Window", (char*)0, (char*)0, "Work [this] OA", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_12_graf_8 = { &kmclass_12_graf_9, (BrActFlag)16,
 "Print", (char*)0, (char*)0, "Picture/Print", (SUBROUTINE*)0, (IntFunc*)0,
 BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_12_graf_7 = { &kmclass_12_graf_8, (BrActFlag)16,
 "Do LaTex...", (char*)0, (char*)0, "-Picture/Print paw.tex", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_12_graf_6 = { &kmclass_12_graf_7, (BrActFlag)16,
 "Do Encapsulated PostScript...", (char*)0, (char*)0,
 "-Picture/Print paw.eps", (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF,
 (BrClass*)0 };
static BrAction kmclass_12_graf_5 = { &kmclass_12_graf_6, (BrActFlag)18,
 "Do PostScript...", (char*)0, (char*)0, "-Picture/Print paw.ps",
 (SUBROUTINE*)0, (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_12_graf_4 = { &kmclass_12_graf_5, (BrActFlag)16,
 "Double Buffer Off", (char*)0, (char*)0, "Igset 2BUF 0", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_12_graf_3 = { &kmclass_12_graf_4, (BrActFlag)18,
 "Double Buffer On", (char*)0, (char*)0, "Igset 2BUF 1", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_12_graf_2 = { &kmclass_12_graf_3, (BrActFlag)18,
 "Style Panel... ", (char*)0, (char*)0, (char*)0, (SUBROUTINE*)0,
 show_histoStyle, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_12_graf_1 = { &kmclass_12_graf_2, (BrActFlag)16,
 "Plot", (char*)0, (char*)0, "Picture/Plot", (SUBROUTINE*)0, (IntFunc*)0,
 BRACT_GRAF, (BrClass*)0 };
static KmClass kmclass_12 = { &kmclass_13, 0, "win", "Graphics Window",
 (char*)0, (KmIcon*)0, (char*)0, (KmIcon*)0, (SUBROUTINE*)0, (IntFunc*)0,
 (BrAction*)0, &kmclass_12_graf_1, 0 };

static BrAction kmclass_11_cont_5 = { (BrAction*)0, (BrActFlag)17, "Delete",
 (char*)0, (char*)0, "Picture/Delete [this]", (SUBROUTINE*)0, (IntFunc*)0,
 BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_11_cont_4 = { &kmclass_11_cont_5, (BrActFlag)17,
 "Rename", (char*)0, (char*)0, "Picture/Rename PNAME1=[this]", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_11_cont_3 = { &kmclass_11_cont_4, (BrActFlag)17,
 "Create", (char*)0, (char*)0, "Picture/Create", (SUBROUTINE*)0, (IntFunc*)0,
 BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_11_cont_2 = { &kmclass_11_cont_3, (BrActFlag)16,
 "Do PostScript", (char*)0, (char*)0,
 "for/file 66 [this].ps;meta -66 -111;pi/pl [this];close 66", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_11_cont_1 = { &kmclass_11_cont_2, (BrActFlag)16,
 "Plot", (char*)0, (char*)0, "Picture/Plot [this]", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static KmClass kmclass_11 = { &kmclass_12, 0, "pict", "Picture", "big_pict",
 (KmIcon*)0, "sm_pict", (KmIcon*)0, (SUBROUTINE*)0, (IntFunc*)0,
 &kmclass_11_cont_1, (BrAction*)0, 0 };

static BrAction kmclass_10_cont_3 = { (BrAction*)0, (BrActFlag)16, "Print",
 (char*)0, (char*)0, "Ntuple/Print [this]", (SUBROUTINE*)0, (IntFunc*)0,
 BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_10_cont_2 = { &kmclass_10_cont_3, (BrActFlag)18,
 "Project...", (char*)0, (char*)0, "-Ntuple/Proj IDN=[this].", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_10_cont_1 = { &kmclass_10_cont_2, (BrActFlag)16,
 "Open Ntuple Viewer", (char*)0, (char*)0, (char*)0, (SUBROUTINE*)0,
 default_action, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_10_graf_3 = { (BrAction*)0, (BrActFlag)16, "Print",
 (char*)0, (char*)0, "Ntuple/Print [this]", (SUBROUTINE*)0, (IntFunc*)0,
 BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_10_graf_2 = { &kmclass_10_graf_3, (BrActFlag)18,
 "Project...", (char*)0, (char*)0, "-Ntuple/Proj IDN=[this].", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_10_graf_1 = { &kmclass_10_graf_2, (BrActFlag)16,
 "Open Ntuple Viewer", (char*)0, (char*)0, (char*)0, (SUBROUTINE*)0,
 default_action, BRACT_GRAF, (BrClass*)0 };
static KmClass kmclass_10 = { &kmclass_11, 0, "ntuple", "Ntuple", "big_nt",
 (KmIcon*)0, "sm_nt", (KmIcon*)0, (SUBROUTINE*)0, (IntFunc*)0,
 &kmclass_10_cont_1, &kmclass_10_graf_1, 0 };

static BrAction kmclass_9_cont_12 = { (BrAction*)0, (BrActFlag)17, "Delete",
 (char*)0, (char*)0, "Histo/Hio/Hscratch [this]", (SUBROUTINE*)0, (IntFunc*)0,
 BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_9_cont_11 = { &kmclass_9_cont_12, (BrActFlag)16,
 "Reset", (char*)0, (char*)0, "Histo/Op/Reset [this]", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_9_cont_10 = { &kmclass_9_cont_11, (BrActFlag)18,
 "Copy", (char*)0, (char*)0, "Histo/Copy [this]", (SUBROUTINE*)0, (IntFunc*)0,
 BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_9_cont_9 = { &kmclass_9_cont_10, (BrActFlag)16,
 "Smooth...", (char*)0, (char*)0, "-Smooth [this]", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_9_cont_8 = { &kmclass_9_cont_9, (BrActFlag)18,
 "Smooth", (char*)0, (char*)0, "Smooth [this]", (SUBROUTINE*)0, (IntFunc*)0,
 BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_9_cont_7 = { &kmclass_9_cont_8, (BrActFlag)16,
 "Band Y", (char*)0, (char*)0,
 "BanY [this]; Hi/Proj [this]; Hi/Plot [this].banY.1", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_9_cont_6 = { &kmclass_9_cont_7, (BrActFlag)16,
 "Band X", (char*)0, (char*)0,
 "BanX [this]; Hi/Proj [this]; Hi/Plot [this].banX.1", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_9_cont_5 = { &kmclass_9_cont_6, (BrActFlag)16,
 "Slice Y", (char*)0, (char*)0,
 "SliY [this]; Hi/Proj [this]; Hi/Plot [this].sliY.1", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_9_cont_4 = { &kmclass_9_cont_5, (BrActFlag)16,
 "Slice X", (char*)0, (char*)0,
 "SliX [this]; Hi/Proj [this]; Hi/Plot [this].sliX.1", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_9_cont_3 = { &kmclass_9_cont_4, (BrActFlag)16,
 "Project Y", (char*)0, (char*)0,
 "ProY [this]; Hi/Proj [this]; Hi/Plot [this].proY", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_9_cont_2 = { &kmclass_9_cont_3, (BrActFlag)18,
 "Project X", (char*)0, (char*)0,
 "ProX [this]; Hi/Proj [this]; Hi/Plot [this].proX", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_9_cont_1 = { &kmclass_9_cont_2, (BrActFlag)16, "Plot",
 (char*)0, (char*)0, (char*)0, (SUBROUTINE*)0, default_action, BRACT_CONT,
 (BrClass*)0 };
static BrAction kmclass_9_graf_23 = { (BrAction*)0, (BrActFlag)16, "Default",
 (char*)0, (char*)0, "Histo/Plot [this] SCAT", (SUBROUTINE*)0,
 default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_9_graf_22 = { &kmclass_9_graf_23, (BrActFlag)16,
 "Text", (char*)0, (char*)0, "Histo/Plot [this] TEXT", (SUBROUTINE*)0,
 default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_9_graf_21 = { &kmclass_9_graf_22, (BrActFlag)16,
 "Arrow Plot", (char*)0, (char*)0, "Histo/Plot [this] ARR", (SUBROUTINE*)0,
 default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_9_graf_20 = { &kmclass_9_graf_21, (BrActFlag)16,
 "Filled Contour Plot", (char*)0, (char*)0,
 "Set NCOl 28;Pal 1;Conto [this] 20 3", (SUBROUTINE*)0, default_G_action,
 BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_9_graf_19 = { &kmclass_9_graf_20, (BrActFlag)16,
 "Contour Plot", (char*)0, (char*)0, "Histo/Plot [this] CONT", (SUBROUTINE*)0,
 default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_9_graf_18 = { &kmclass_9_graf_19, (BrActFlag)16,
 "Color Level Lego", (char*)0, (char*)0, "Histo/Plot [this] LEGO2",
 (SUBROUTINE*)0, default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_9_graf_17 = { &kmclass_9_graf_18, (BrActFlag)16,
 "Filled Lego", (char*)0, (char*)0, "Histo/Plot [this] LEGO1", (SUBROUTINE*)0,
 default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_9_graf_16 = { &kmclass_9_graf_17, (BrActFlag)16,
 "Hidden Lines Lego", (char*)0, (char*)0, "Histo/Plot [this] LEGO",
 (SUBROUTINE*)0, default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_9_graf_15 = { &kmclass_9_graf_16, (BrActFlag)16,
 "Gouraud Shaded Surface", (char*)0, (char*)0, "Histo/Plot [this] SURF4",
 (SUBROUTINE*)0, default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_9_graf_14 = { &kmclass_9_graf_15, (BrActFlag)16,
 "Surface and Contour", (char*)0, (char*)0, "Histo/Plot [this] SURF3",
 (SUBROUTINE*)0, default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_9_graf_13 = { &kmclass_9_graf_14, (BrActFlag)16,
 "Color Level Surface (2)", (char*)0, (char*)0, "Histo/Plot [this] SURF2",
 (SUBROUTINE*)0, default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_9_graf_12 = { &kmclass_9_graf_13, (BrActFlag)16,
 "Color Level Surface (1)", (char*)0, (char*)0, "Histo/Plot [this] SURF1",
 (SUBROUTINE*)0, default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_9_graf_11 = { &kmclass_9_graf_12, (BrActFlag)16,
 "Hidden Lines Surface", (char*)0, (char*)0, "Histo/Plot [this] SURF",
 (SUBROUTINE*)0, default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_9_graf_10 = { &kmclass_9_graf_11, (BrActFlag)16,
 "Color", (char*)0, (char*)0, "Histo/Plot [this] COLZ", (SUBROUTINE*)0,
 default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_9_graf_9 = { &kmclass_9_graf_10, (BrActFlag)18,
 "Boxes", (char*)0, (char*)0, "Histo/Plot [this] BOX", (SUBROUTINE*)0,
 default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_9_graf_8 = { &kmclass_9_graf_9, (BrActFlag)16,
 "Smooth...", (char*)0, (char*)0, "-Smooth [this]", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_9_graf_7 = { &kmclass_9_graf_8, (BrActFlag)18,
 "Smooth", (char*)0, (char*)0, "Smooth [this]", (SUBROUTINE*)0, (IntFunc*)0,
 BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_9_graf_6 = { &kmclass_9_graf_7, (BrActFlag)16,
 "Band Y", (char*)0, (char*)0,
 "BanY [this]; Hi/Proj [this]; Hi/Plot [this].banY.1", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_9_graf_5 = { &kmclass_9_graf_6, (BrActFlag)16,
 "Band X", (char*)0, (char*)0,
 "BanX [this]; Hi/Proj [this]; Hi/Plot [this].banX.1", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_9_graf_4 = { &kmclass_9_graf_5, (BrActFlag)16,
 "Slice Y", (char*)0, (char*)0,
 "SliY [this]; Hi/Proj [this]; Hi/Plot [this].sliY.1", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_9_graf_3 = { &kmclass_9_graf_4, (BrActFlag)16,
 "Slice X", (char*)0, (char*)0,
 "SliX [this]; Hi/Proj [this]; Hi/Plot [this].sliX.1", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_9_graf_2 = { &kmclass_9_graf_3, (BrActFlag)16,
 "Project Y", (char*)0, (char*)0,
 "ProY [this]; Hi/Proj [this]; Hi/Plot [this].proY", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_9_graf_1 = { &kmclass_9_graf_2, (BrActFlag)16,
 "Project X", (char*)0, (char*)0,
 "ProX [this]; Hi/Proj [this]; Hi/Plot [this].proX", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_GRAF, (BrClass*)0 };
static KmClass kmclass_9 = { &kmclass_10, 0, "2d", "2d-Histogram", "big_2d",
 (KmIcon*)0, "sm_2d", (KmIcon*)0, (SUBROUTINE*)0, (IntFunc*)0,
 &kmclass_9_cont_1, &kmclass_9_graf_1, 0 };

static BrAction kmclass_8_cont_13 = { (BrAction*)0, (BrActFlag)17, "Delete",
 (char*)0, (char*)0, "Histo/Hio/Hscratch [this]", (SUBROUTINE*)0, (IntFunc*)0,
 BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_8_cont_12 = { &kmclass_8_cont_13, (BrActFlag)16,
 "Reset", (char*)0, (char*)0, "Histo/Op/Reset [this]", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_8_cont_11 = { &kmclass_8_cont_12, (BrActFlag)18,
 "Copy", (char*)0, (char*)0, "Histo/Copy [this]", (SUBROUTINE*)0, (IntFunc*)0,
 BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_8_cont_10 = { &kmclass_8_cont_11, (BrActFlag)16,
 "Smooth...", (char*)0, (char*)0, "-Smooth [this]", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_8_cont_9 = { &kmclass_8_cont_10, (BrActFlag)18,
 "Smooth", (char*)0, (char*)0, "Smooth [this]", (SUBROUTINE*)0, (IntFunc*)0,
 BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_8_cont_8 = { &kmclass_8_cont_9, (BrActFlag)16,
 "Fit Linear", (char*)0, (char*)0, "Histo/Fit [this] P1", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_8_cont_7 = { &kmclass_8_cont_8, (BrActFlag)16,
 "Fit Const", (char*)0, (char*)0, "Histo/Fit [this] P0", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_8_cont_6 = { &kmclass_8_cont_7, (BrActFlag)16,
 "Fit Exp", (char*)0, (char*)0, "Histo/Fit [this] E", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_8_cont_5 = { &kmclass_8_cont_6, (BrActFlag)16,
 "Fit Gauss", (char*)0, (char*)0, "Histo/Fit [this] G", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_8_cont_4 = { &kmclass_8_cont_5, (BrActFlag)16,
 "Fitting panel...", (char*)0, (char*)0, (char*)0, (SUBROUTINE*)0,
 fitting_action, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_8_cont_3 = { &kmclass_8_cont_4, (BrActFlag)18,
 "Fit command...", (char*)0, (char*)0, "Histo/Fit [this]", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_8_cont_2 = { &kmclass_8_cont_3, (BrActFlag)16,
 "Overlay", (char*)0, (char*)0, "Histo/plot [this] S", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_8_cont_1 = { &kmclass_8_cont_2, (BrActFlag)16, "Plot",
 (char*)0, (char*)0, (char*)0, (SUBROUTINE*)0, default_action, BRACT_CONT,
 (BrClass*)0 };
static BrAction kmclass_8_graf_21 = { (BrAction*)0, (BrActFlag)16, "Default",
 (char*)0, (char*)0, "Histo/Plot [this]", (SUBROUTINE*)0, default_G_action,
 BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_8_graf_20 = { &kmclass_8_graf_21, (BrActFlag)16,
 "Filled Lego", (char*)0, (char*)0, "Histo/Plot [this] LEGO1", (SUBROUTINE*)0,
 default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_8_graf_19 = { &kmclass_8_graf_20, (BrActFlag)16,
 "Lego", (char*)0, (char*)0, "Histo/Plot [this] LEGO", (SUBROUTINE*)0,
 default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_8_graf_18 = { &kmclass_8_graf_19, (BrActFlag)16,
 "Error: Smoothed Area", (char*)0, (char*)0, "Histo/Plot [this] E4",
 (SUBROUTINE*)0, default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_8_graf_17 = { &kmclass_8_graf_18, (BrActFlag)16,
 "Error: Filled Area", (char*)0, (char*)0, "Histo/Plot [this] E3",
 (SUBROUTINE*)0, default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_8_graf_16 = { &kmclass_8_graf_17, (BrActFlag)16,
 "Error Rectangles", (char*)0, (char*)0, "Histo/Plot [this] E2",
 (SUBROUTINE*)0, default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_8_graf_15 = { &kmclass_8_graf_16, (BrActFlag)16,
 "Error Bars (lines)", (char*)0, (char*)0, "Histo/Plot [this] E1",
 (SUBROUTINE*)0, default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_8_graf_14 = { &kmclass_8_graf_15, (BrActFlag)16,
 "Error Bars", (char*)0, (char*)0, "Histo/Plot [this] E", (SUBROUTINE*)0,
 default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_8_graf_13 = { &kmclass_8_graf_14, (BrActFlag)16,
 "Stars", (char*)0, (char*)0, "Histo/Plot [this] *", (SUBROUTINE*)0,
 default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_8_graf_12 = { &kmclass_8_graf_13, (BrActFlag)16,
 "Marker", (char*)0, (char*)0, "Histo/Plot [this] P", (SUBROUTINE*)0,
 default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_8_graf_11 = { &kmclass_8_graf_12, (BrActFlag)16,
 "Bar Chart", (char*)0, (char*)0, "Histo/Plot [this] B", (SUBROUTINE*)0,
 default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_8_graf_10 = { &kmclass_8_graf_11, (BrActFlag)16,
 "Curve", (char*)0, (char*)0, "Histo/Plot [this] C", (SUBROUTINE*)0,
 default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_8_graf_9 = { &kmclass_8_graf_10, (BrActFlag)18,
 "Line", (char*)0, (char*)0, "Histo/Plot [this] L", (SUBROUTINE*)0,
 default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_8_graf_8 = { &kmclass_8_graf_9, (BrActFlag)16,
 "Smooth...", (char*)0, (char*)0, "-Smooth [this]", (SUBROUTINE*)0,
 default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_8_graf_7 = { &kmclass_8_graf_8, (BrActFlag)18,
 "Smooth", (char*)0, (char*)0, "Smooth [this]", (SUBROUTINE*)0,
 default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_8_graf_6 = { &kmclass_8_graf_7, (BrActFlag)16,
 "Fit Linear", (char*)0, (char*)0, "Histo/Fit [this] P1", (SUBROUTINE*)0,
 default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_8_graf_5 = { &kmclass_8_graf_6, (BrActFlag)16,
 "Fit Const", (char*)0, (char*)0, "Histo/Fit [this] P0", (SUBROUTINE*)0,
 default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_8_graf_4 = { &kmclass_8_graf_5, (BrActFlag)16,
 "Fit Exp", (char*)0, (char*)0, "Histo/Fit [this] E", (SUBROUTINE*)0,
 default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_8_graf_3 = { &kmclass_8_graf_4, (BrActFlag)16,
 "Fit Gauss", (char*)0, (char*)0, "Histo/Fit [this] G", (SUBROUTINE*)0,
 default_G_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_8_graf_2 = { &kmclass_8_graf_3, (BrActFlag)16,
 "Fitting panel...", (char*)0, (char*)0, (char*)0, (SUBROUTINE*)0,
 fitting_action, BRACT_GRAF, (BrClass*)0 };
static BrAction kmclass_8_graf_1 = { &kmclass_8_graf_2, (BrActFlag)16,
 "Fit command...", (char*)0, (char*)0, "Histo/Fit [this]", (SUBROUTINE*)0,
 default_G_action, BRACT_GRAF, (BrClass*)0 };
static KmClass kmclass_8 = { &kmclass_9, 0, "1d", "1d-Histogram", "big_1d",
 (KmIcon*)0, "sm_1d", (KmIcon*)0, (SUBROUTINE*)0, (IntFunc*)0,
 &kmclass_8_cont_1, &kmclass_8_graf_1, 0 };

static BrAction kmclass_7_cont_1 = { (BrAction*)0, (BrActFlag)16, "List",
 (char*)0, (char*)0, "Cdir [path]", (SUBROUTINE*)0, (IntFunc*)0, BRACT_CONT,
 (BrClass*)0 };
static KmClass kmclass_7 = { &kmclass_8, 1, "dir", "Directory", "big_dir",
 (KmIcon*)0, "sm_dir", (KmIcon*)0, (SUBROUTINE*)0, (IntFunc*)0,
 &kmclass_7_cont_1, (BrAction*)0, 0 };

static BrAction kmclass_6_cont_2 = { (BrAction*)0, (BrActFlag)17,
 "Delete Chain Entry", (char*)0, (char*)0, (char*)0, (SUBROUTINE*)0,
 bdelete_entry, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_6_cont_1 = { &kmclass_6_cont_2, (BrActFlag)16, "List",
 (char*)0, (char*)0, (char*)0, (SUBROUTINE*)0, (IntFunc*)0, BRACT_CONT,
 (BrClass*)0 };
static KmClass kmclass_6 = { &kmclass_7, 0, "entry", "Chain Entry",
 "big_leaf", (KmIcon*)0, "sm_leaf", (KmIcon*)0, (SUBROUTINE*)0, (IntFunc*)0,
 &kmclass_6_cont_1, (BrAction*)0, 0 };

static BrAction kmclass_5_cont_3 = { (BrAction*)0, (BrActFlag)19,
 "Delete Chain", (char*)0, (char*)0, "Chain -[this]", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_5_cont_2 = { &kmclass_5_cont_3, (BrActFlag)16,
 "Show Tree", (char*)0, (char*)0, "Chain [this]>", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_5_cont_1 = { &kmclass_5_cont_2, (BrActFlag)17, "List",
 (char*)0, (char*)0, (char*)0, (SUBROUTINE*)0, (IntFunc*)0, BRACT_CONT,
 (BrClass*)0 };
static KmClass kmclass_5 = { &kmclass_6, 1, "chain", "Chain", "big_chain",
 (KmIcon*)0, "sm_chain", (KmIcon*)0, (SUBROUTINE*)0, (IntFunc*)0,
 &kmclass_5_cont_1, (BrAction*)0, 0 };

static BrAction kmclass_4_cont_2 = { (BrAction*)0, (BrActFlag)17, "Remove",
 (char*)0, (char*)0, "Piaf/Rm [path]/[this]", (SUBROUTINE*)0, (IntFunc*)0,
 BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_4_cont_1 = { &kmclass_4_cont_2, (BrActFlag)17, "Get",
 (char*)0, (char*)0, "Piaf/Get [path]/[this] [this] T", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static KmClass kmclass_4 = { &kmclass_5, 0, "piafro", "Piaf Read-only File",
 "big_fro", (KmIcon*)0, "sm_fro", (KmIcon*)0, (SUBROUTINE*)0, (IntFunc*)0,
 &kmclass_4_cont_1, (BrAction*)0, 0 };

static BrAction kmclass_3_cont_3 = { (BrAction*)0, (BrActFlag)17, "Remove",
 (char*)0, (char*)0, "Piaf/Rm [path]/[this]", (SUBROUTINE*)0, (IntFunc*)0,
 BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_3_cont_2 = { &kmclass_3_cont_3, (BrActFlag)17, "Get",
 (char*)0, (char*)0, "Piaf/Get [path]/[this] [this] RZ", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_3_cont_1 = { &kmclass_3_cont_2, (BrActFlag)17, "Open",
 (char*)0, (char*)0, "Histo/File 0 //piaf/[path]/[this] 0", (SUBROUTINE*)0,
 (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static KmClass kmclass_3 = { &kmclass_4, 0, "piafhb", "Piaf Hbook File",
 "big_hbook", (KmIcon*)0, "sm_hbook", (KmIcon*)0, (SUBROUTINE*)0, (IntFunc*)0,
 &kmclass_3_cont_1, (BrAction*)0, 0 };

static BrAction kmclass_2_cont_2 = { (BrAction*)0, (BrActFlag)17, "Greset",
 (char*)0, (char*)0, "Greset 0", (SUBROUTINE*)0, (IntFunc*)0, BRACT_CONT,
 (BrClass*)0 };
static BrAction kmclass_2_cont_1 = { &kmclass_2_cont_2, (BrActFlag)17, "Open",
 (char*)0, (char*)0, "Global [that]", (SUBROUTINE*)0, (IntFunc*)0, BRACT_CONT,
 (BrClass*)0 };
static KmClass kmclass_2 = { &kmclass_3, 0, "global", "Global section",
 "big_hbook", (KmIcon*)0, "sm_hbook", (KmIcon*)0, (SUBROUTINE*)0, (IntFunc*)0,
 &kmclass_2_cont_1, (BrAction*)0, 0 };

static BrAction kmclass_1_cont_2 = { (BrAction*)0, (BrActFlag)17,
 "Open Update Mode", (char*)0, (char*)0, "Histo/File 0 [that] 0 -XU",
 (SUBROUTINE*)0, (IntFunc*)0, BRACT_CONT, (BrClass*)0 };
static BrAction kmclass_1_cont_1 = { &kmclass_1_cont_2, (BrActFlag)17, "Open",
 (char*)0, (char*)0, "Histo/File 0 [that] 0 -X", (SUBROUTINE*)0, (IntFunc*)0,
 BRACT_CONT, (BrClass*)0 };
static KmClass kmclass_1 = { &kmclass_2, 0, "hbook", "Hbook File",
 "big_hbook", (KmIcon*)0, "sm_hbook", (KmIcon*)0, (SUBROUTINE*)0, (IntFunc*)0,
 &kmclass_1_cont_1, (BrAction*)0, 0 };

static unsigned char kmicons_16_bitmap[] = { 255, 255, 3, 1, 0, 2, 1, 0, 2, 1,
 0, 2, 125, 248, 2, 57, 112, 2, 57, 112, 2, 57, 112, 2, 121, 120, 2, 249, 127,
 2, 249, 127, 2, 121, 120, 2, 57, 112, 2, 57, 112, 2, 57, 112, 2, 57, 112, 2,
 57, 112, 2, 125, 248, 2, 1, 0, 2, 1, 0, 2, 1, 0, 2, 255, 255, 3 };
static KmIcon kmicons_16 = { (KmIcon*)0, "sm_hbook", 18, 22,
 (char*)kmicons_16_bitmap, (KmPixmap)0, (KmPixmap)0 };

static unsigned char kmicons_15_bitmap[] = { 255, 255, 255, 15, 1, 0, 0, 8, 1,
 0, 0, 8, 1, 0, 0, 8, 1, 0, 0, 8, 1, 0, 0, 8, 241, 3, 252, 8, 225, 1, 120, 8,
 225, 1, 120, 8, 225, 1, 120, 8, 225, 1, 120, 8, 225, 1, 120, 8, 225, 1, 120,
 8, 225, 1, 120, 8, 225, 1, 120, 8, 225, 1, 120, 8, 225, 3, 124, 8, 225, 255,
 127, 8, 225, 255, 127, 8, 225, 255, 127, 8, 225, 3, 124, 8, 225, 1, 120, 8,
 225, 1, 120, 8, 225, 1, 120, 8, 225, 1, 120, 8, 225, 1, 120, 8, 225, 1, 120,
 8, 225, 1, 120, 8, 225, 1, 120, 8, 225, 1, 120, 8, 225, 1, 120, 8, 225, 1,
 120, 8, 241, 3, 252, 8, 1, 0, 0, 8, 1, 0, 0, 8, 1, 0, 0, 8, 1, 0, 0, 8, 255,
 255, 255, 15 };
static KmIcon kmicons_15 = { &kmicons_16, "big_hbook", 28, 38,
 (char*)kmicons_15_bitmap, (KmPixmap)0, (KmPixmap)0 };

static unsigned char kmicons_14_bitmap[] = { 255, 255, 3, 1, 0, 2, 113, 0, 2,
 145, 32, 2, 81, 81, 2, 161, 74, 2, 161, 78, 2, 65, 81, 2, 125, 73, 2, 5, 70,
 2, 201, 35, 2, 17, 20, 2, 33, 24, 2, 193, 15, 2, 1, 8, 2, 1, 24, 2, 1, 16, 2,
 1, 24, 2, 1, 0, 2, 1, 0, 2, 1, 0, 2, 255, 255, 3 };
static KmIcon kmicons_14 = { &kmicons_15, "sm_leaf", 18, 22,
 (char*)kmicons_14_bitmap, (KmPixmap)0, (KmPixmap)0 };

static unsigned char kmicons_13_bitmap[] = { 255, 255, 255, 15, 1, 0, 0, 8, 1,
 0, 0, 8, 1, 0, 0, 8, 1, 0, 0, 8, 1, 0, 0, 8, 193, 1, 0, 8, 129, 6, 0, 8, 129,
 12, 0, 8, 129, 26, 0, 8, 1, 37, 0, 8, 1, 89, 48, 8, 1, 147, 40, 8, 1, 182,
 108, 8, 97, 164, 67, 8, 161, 40, 81, 8, 161, 79, 80, 8, 97, 192, 72, 8, 65,
 131, 102, 8, 193, 188, 33, 8, 129, 225, 48, 8, 1, 3, 17, 8, 1, 6, 25, 8, 1,
 60, 12, 8, 1, 224, 7, 8, 1, 0, 3, 8, 1, 0, 6, 8, 1, 0, 4, 8, 1, 0, 4, 8, 1,
 0, 4, 8, 1, 0, 6, 8, 1, 0, 3, 8, 1, 0, 1, 8, 1, 0, 0, 8, 1, 0, 0, 8, 1, 0, 0,
 8, 1, 0, 0, 8, 255, 255, 255, 15 };
static KmIcon kmicons_13 = { &kmicons_14, "big_leaf", 28, 38,
 (char*)kmicons_13_bitmap, (KmPixmap)0, (KmPixmap)0 };

static unsigned char kmicons_12_bitmap[] = { 255, 127, 14, 1, 0, 11, 1, 128,
 13, 169, 170, 2, 81, 1, 9, 169, 204, 15, 81, 86, 13, 41, 235, 14, 145, 85,
 13, 201, 202, 14, 97, 101, 13, 169, 178, 14, 65, 89, 13, 201, 172, 14, 97,
 86, 13, 241, 171, 14, 249, 85, 13, 172, 170, 14, 254, 255, 15, 255, 255, 15 };
static KmIcon kmicons_12 = { &kmicons_13, "sm_chain", 20, 20,
 (char*)kmicons_12_bitmap, (KmPixmap)0, (KmPixmap)0 };

static unsigned char kmicons_11_bitmap[] = { 255, 255, 255, 57, 1, 0, 0, 40,
 1, 0, 0, 52, 169, 170, 42, 58, 81, 85, 21, 29, 169, 170, 170, 10, 81, 85, 21,
 38, 169, 170, 42, 51, 81, 85, 149, 57, 169, 170, 192, 63, 81, 85, 102, 53,
 169, 42, 171, 58, 81, 149, 117, 53, 169, 202, 170, 58, 81, 101, 101, 53, 169,
 178, 178, 58, 81, 89, 89, 53, 169, 170, 172, 58, 81, 81, 86, 53, 169, 50,
 171, 58, 81, 153, 85, 53, 9, 252, 170, 58, 97, 86, 85, 53, 49, 175, 170, 58,
 217, 85, 85, 53, 172, 172, 170, 58, 86, 86, 85, 53, 63, 171, 170, 58, 159,
 255, 255, 63, 207, 255, 255, 63 };
static KmIcon kmicons_11 = { &kmicons_12, "big_chain", 30, 30,
 (char*)kmicons_11_bitmap, (KmPixmap)0, (KmPixmap)0 };

static unsigned char kmicons_10_bitmap[] = { 255, 255, 15, 1, 0, 8, 1, 0, 12,
 169, 170, 14, 81, 85, 13, 169, 190, 14, 81, 96, 13, 41, 198, 14, 81, 78, 13,
 41, 192, 14, 81, 67, 13, 41, 193, 14, 81, 96, 13, 169, 166, 14, 81, 101, 13,
 169, 176, 14, 81, 83, 13, 169, 190, 14, 253, 255, 15, 255, 255, 15 };
static KmIcon kmicons_10 = { &kmicons_11, "sm_pict", 20, 20,
 (char*)kmicons_10_bitmap, (KmPixmap)0, (KmPixmap)0 };

static unsigned char kmicons_9_bitmap[] = { 255, 255, 255, 63, 1, 0, 0, 32, 1,
 0, 0, 48, 169, 170, 170, 58, 81, 85, 85, 53, 169, 234, 191, 58, 81, 21, 96,
 53, 169, 10, 140, 58, 81, 245, 186, 53, 169, 174, 162, 59, 81, 249, 54, 53,
 169, 170, 156, 59, 81, 113, 192, 53, 169, 0, 224, 58, 81, 1, 112, 53, 169,
 56, 184, 58, 81, 61, 92, 53, 169, 60, 172, 58, 81, 193, 85, 53, 169, 64, 173,
 58, 81, 163, 85, 53, 169, 98, 173, 58, 81, 205, 84, 53, 169, 10, 174, 58, 81,
 245, 87, 53, 169, 170, 170, 58, 81, 85, 85, 53, 169, 170, 170, 58, 253, 255,
 255, 63, 255, 255, 255, 63 };
static KmIcon kmicons_9 = { &kmicons_10, "big_pict", 30, 30,
 (char*)kmicons_9_bitmap, (KmPixmap)0, (KmPixmap)0 };

static unsigned char kmicons_8_bitmap[] = { 255, 255, 15, 1, 0, 8, 1, 0, 12,
 81, 85, 13, 169, 170, 14, 1, 21, 12, 41, 128, 14, 81, 85, 13, 169, 170, 14,
 81, 85, 13, 169, 170, 14, 81, 85, 13, 169, 170, 14, 81, 85, 13, 253, 255, 15,
 255, 255, 15 };
static KmIcon kmicons_8 = { &kmicons_9, "sm_dir", 20, 16,
 (char*)kmicons_8_bitmap, (KmPixmap)0, (KmPixmap)0 };

static unsigned char kmicons_7_bitmap[] = { 255, 255, 255, 63, 1, 0, 0, 32, 1,
 0, 0, 48, 169, 170, 170, 58, 81, 85, 85, 53, 169, 170, 170, 58, 1, 84, 21,
 48, 1, 168, 10, 48, 81, 1, 64, 53, 169, 2, 160, 58, 81, 85, 85, 53, 169, 170,
 170, 58, 81, 85, 85, 53, 169, 170, 170, 58, 81, 85, 85, 53, 169, 170, 170,
 58, 81, 85, 85, 53, 169, 170, 170, 58, 81, 85, 85, 53, 169, 170, 170, 58, 81,
 85, 85, 53, 253, 255, 255, 63, 255, 255, 255, 63 };
static KmIcon kmicons_7 = { &kmicons_8, "big_dir", 30, 23,
 (char*)kmicons_7_bitmap, (KmPixmap)0, (KmPixmap)0 };

static unsigned char kmicons_6_bitmap[] = { 255, 255, 15, 1, 0, 8, 1, 0, 12,
 169, 170, 14, 241, 255, 13, 25, 0, 15, 241, 255, 13, 217, 182, 15, 177, 109,
 13, 153, 36, 15, 241, 255, 13, 217, 182, 15, 177, 109, 13, 249, 255, 15, 145,
 36, 13, 185, 109, 15, 241, 255, 13, 169, 170, 14, 253, 255, 15, 255, 255, 15
 };
static KmIcon kmicons_6 = { &kmicons_7, "sm_nt", 20, 20,
 (char*)kmicons_6_bitmap, (KmPixmap)0, (KmPixmap)0 };

static unsigned char kmicons_5_bitmap[] = { 255, 255, 255, 63, 1, 0, 0, 32, 1,
 0, 0, 48, 169, 170, 170, 58, 81, 85, 85, 53, 249, 255, 255, 63, 17, 0, 0, 52,
 25, 0, 0, 60, 241, 255, 255, 55, 89, 85, 181, 62, 49, 51, 19, 52, 25, 17, 49,
 60, 241, 255, 255, 55, 89, 85, 181, 62, 49, 51, 19, 52, 25, 17, 49, 60, 241,
 255, 255, 55, 89, 85, 181, 62, 49, 51, 19, 52, 25, 17, 49, 60, 241, 255, 255,
 55, 89, 85, 181, 62, 49, 51, 19, 52, 25, 17, 49, 60, 49, 51, 19, 52, 249,
 255, 255, 63, 81, 85, 85, 53, 169, 170, 170, 58, 253, 255, 255, 63, 255, 255,
 255, 63 };
static KmIcon kmicons_5 = { &kmicons_6, "big_nt", 30, 30,
 (char*)kmicons_5_bitmap, (KmPixmap)0, (KmPixmap)0 };

static unsigned char kmicons_4_bitmap[] = { 255, 255, 15, 1, 0, 8, 169, 249,
 13, 85, 101, 14, 169, 149, 12, 213, 100, 14, 121, 8, 13, 13, 240, 12, 233, 1,
 14, 21, 226, 13, 233, 180, 14, 29, 85, 13, 233, 180, 14, 21, 82, 13, 233,
 169, 14, 13, 84, 13, 57, 170, 14, 213, 85, 13, 253, 255, 15, 255, 255, 15 };
static KmIcon kmicons_4 = { &kmicons_5, "sm_2d", 20, 20,
 (char*)kmicons_4_bitmap, (KmPixmap)0, (KmPixmap)0 };

static unsigned char kmicons_3_bitmap[] = { 255, 255, 255, 63, 1, 0, 0, 32, 1,
 0, 0, 48, 169, 170, 170, 58, 81, 95, 85, 53, 233, 160, 254, 58, 49, 79, 3,
 53, 153, 144, 121, 58, 81, 38, 132, 52, 89, 41, 50, 57, 81, 38, 74, 53, 153,
 144, 50, 57, 33, 143, 132, 52, 105, 64, 121, 58, 209, 60, 2, 53, 169, 64, 60,
 59, 81, 128, 4, 54, 41, 63, 243, 60, 145, 64, 8, 55, 89, 158, 100, 60, 81,
 161, 148, 52, 89, 161, 100, 60, 81, 158, 8, 55, 153, 64, 242, 60, 49, 63, 7,
 55, 105, 128, 250, 59, 209, 127, 85, 53, 169, 170, 170, 58, 253, 255, 255,
 63, 255, 255, 255, 63 };
static KmIcon kmicons_3 = { &kmicons_4, "big_2d", 30, 30,
 (char*)kmicons_3_bitmap, (KmPixmap)0, (KmPixmap)0 };

static unsigned char kmicons_2_bitmap[] = { 255, 255, 15, 1, 0, 8, 1, 0, 12,
 169, 170, 14, 209, 85, 13, 105, 171, 14, 81, 93, 13, 105, 183, 14, 81, 117,
 13, 105, 213, 14, 81, 85, 13, 121, 213, 14, 81, 213, 13, 89, 85, 15, 81, 85,
 13, 89, 85, 15, 241, 255, 13, 169, 170, 14, 253, 255, 15, 255, 255, 15 };
static KmIcon kmicons_2 = { &kmicons_3, "sm_1d", 20, 20,
 (char*)kmicons_2_bitmap, (KmPixmap)0, (KmPixmap)0 };

static unsigned char kmicons_1_bitmap[] = { 255, 255, 255, 63, 1, 0, 0, 32, 1,
 0, 0, 48, 169, 170, 170, 58, 81, 85, 85, 53, 169, 170, 170, 58, 81, 125, 85,
 53, 169, 166, 170, 58, 81, 101, 85, 53, 169, 166, 175, 58, 81, 101, 89, 53,
 169, 230, 169, 58, 81, 37, 89, 53, 169, 38, 169, 58, 81, 37, 89, 53, 169, 39,
 249, 58, 209, 36, 73, 53, 169, 36, 201, 58, 209, 36, 73, 53, 249, 36, 201,
 59, 145, 36, 73, 54, 153, 36, 73, 58, 145, 36, 73, 54, 153, 36, 73, 58, 145,
 36, 73, 54, 153, 36, 73, 58, 241, 255, 255, 55, 169, 170, 170, 58, 253, 255,
 255, 63, 255, 255, 255, 63 };
static KmIcon kmicons_1 = { &kmicons_2, "big_1d", 30, 30,
 (char*)kmicons_1_bitmap, (KmPixmap)0, (KmPixmap)0 };

static KmButton kmbuttons_1 = { (KmButton*)0, "View", " Style Panel ",
 (SUBROUTINE*)0, kxterm_show_style, "kxterm_show_style", "S", "<Key>F4", "F4",
 (KmButtFlag)0, (KmWidget)0 };

  klnkmenu( &_MOTIF, 950303 );
  klnkbrcl( &brclass_1, 950303 );
  klnkkmcl( &kmclass_1, 950303 );
  klnkicon( &kmicons_1, 950303 );
  klnkbutt( &kmbuttons_1, 950303 );
  klnkaddr.graf_info_C = ixmotif;
  klnkaddr.graf_size_F = igrsiz_;
  klnkaddr.graf_pick_F = igobj_;
  klnkaddr.graf_attr_F = igset_;
  klnkaddr.graf_close_F = iclwk_;
  klnkaddr.user_FallBk_C = get_paw_fallbacks;
  klnkaddr.user_TopWid_C = init_top_level_window;
}


