*
* $Id$
*
* $Log$
* Revision 1.1  1996/02/14 13:10:13  mclareni
* Initial revision
*
*
#ifndef CERNLIB_HIGZ_HIMENU_INC
#define CERNLIB_HIGZ_HIMENU_INC
*
*
* himenu.inc
*
*CMZ :  1.18/00 23/04/93  17.27.57  by  O.Couet
*-- Author :
      COMMON /HIMENU/ Y3,Y4,YT,XSIZ,YSIZ,RINT,REDLOC,NBCHOI,ICUCH,DEC
     +,OTH,TH,XPOS(2),YPOS(2),IRSU,ILSU,XM,XML,XMR,YSTEP,XP,YP
     +,XOPT,IPARA,ISOFT,NBUSER,UTH,USIZ,ISEGM(100),MENNUM


#endif
