*
* $Id$
*
* $Log$
* Revision 1.1  1996/01/19 10:50:13  mclareni
* Initial revision
*
*
#ifndef CERNLIB_HPLOT_HPL2_INC
#define CERNLIB_HPLOT_HPL2_INC
*
*
* hpl2.inc
*
*CMZ :          09/11/95  17.18.57  by  O.Couet
*-- Author :
      COMMON/HPL2/XLOW  ,XHIGH ,YLOW  ,YHIGH ,XFRAC ,YFRAC ,YMMAX
     +    ,YMMIN ,IOFSET,XWDIST,YWDIST,XWIND ,YWIND ,SCMAX ,IXWIN
     +    ,IYWIN ,IWIN  ,ISLIC
     +    ,NCX
     +    ,IWIN0 ,NTWIN ,NTHIST ,NCHIST

#endif
