*
* $Id$
*
* $Log$
* Revision 1.1  1996/02/28 16:23:37  mclareni
* Initial revision
*
*
*
* cdxluns.inc
*
* - - - - - Logical units - - - - - - - - - - - - - - - -
      INTEGER LUNINP
      PARAMETER (LUNINP=5)
*
      INTEGER LUNOUT
      PARAMETER (LUNOUT=6)
*
      INTEGER LUNPRO
      PARAMETER (LUNPRO=9)
*
      INTEGER LUNCMD
      PARAMETER (LUNCMD=10)
*
      INTEGER LUNAMES
      PARAMETER (LUNAMES=80)
* - - - - - - - - - - - - - - - - - - - - - - - - - - - -
*
