*
* $Id$
*
* $Log$
* Revision 1.1  1996/02/15 17:53:40  mclareni
* Initial revision
*
*
*
* comment.inc
*
 
 
C--                THIS PATCH CONTAINS THE ASSEMBLER ROUTINES
C--                WHICH HAVE BEEN CODED IN REENTRANT FORM.
C--
C--                THE PATCHY SEQUENCES REENTR AND REENT1 ARE
C--                DEFINED IN THIS PATCH, BY DEFAULT, AS DUMMY
C--                THEY ARE DEFINED IN PATCH REENTR IN CASE A
C--                REENTRANT VERSION IS DESIRED
 
 
